// resources/js/features/arsip-digital/admin/AdminRequests.jsx
import { useEffect, useRef, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { arsipApi } from '../../../libs/arsip_api';
import { formatArsipError } from '../../../libs/arsip_http';
import { dateTime, lines } from '../../../libs/format';
import { customSwal } from '../../../components/CustomSwal';
import { confirmAction } from '../../../services/dialogs';
import PageHeader from '../../../components/PageHeader';
import StatusChip from '../../../components/StatusChip';
import CustomDataTable from '../../../components/CustomDataTable';
import TargetPicker from '../components/TargetPicker';
import {
    Alert,
    Button,
    Dialog,
    DialogActions,
    DialogContent,
    DialogTitle,
    MenuItem,
    TextField,
} from '@mui/material';
import AddOutlined from '@mui/icons-material/AddOutlined';
import SearchOutlined from '@mui/icons-material/SearchOutlined';
import RefreshOutlined from '@mui/icons-material/RefreshOutlined';
import VisibilityOutlined from '@mui/icons-material/VisibilityOutlined';

const buttonSx = {
    borderRadius: '0.5rem',
    textTransform: 'none',
    fontFamily: 'Plus Jakarta Sans, sans-serif',
};

const emptyForm = {
    title: '',
    description: '',
    deadline_at: '',
    allowed_extensions: 'pdf, jpg, jpeg, png, doc, docx, xls, xlsx',
    max_file_size_mb: '',
    max_files: 1,
    requires_verification: true,
    allow_file_reuse: true,
    close_after_deadline: false,
};

function unwrapList(response) {
    const payload = response?.data ?? response ?? {};
    const list = Array.isArray(payload) ? payload : payload.requests ?? payload.data ?? [];
    return {
        data: Array.isArray(list) ? list : [],
        meta: payload.meta ?? payload.pagination ?? response?.meta ?? null,
    };
}

function unwrapPreview(response) {
    const payload = response?.data ?? response ?? {};
    return payload.preview ?? payload;
}

function requestId(row) {
    return row.request_id ?? row.id;
}

function requestProgress(row) {
    const total = row.assignments_count ?? row.total_assignments ?? row.progress?.total_assignments;
    const submitted = row.submitted_assignments_count ?? row.progress?.submitted;
    const approved = row.approved_assignments_count ?? row.progress?.approved;
    if (total === undefined && submitted === undefined && approved === undefined) return '-';
    return `${submitted ?? 0}/${total ?? 0}${approved !== undefined ? ` · ${approved} approved` : ''}`;
}

function normalizeForm(request) {
    if (!request) return emptyForm;
    return {
        title: request.title || '',
        description: request.description || '',
        deadline_at: request.deadline_at ? String(request.deadline_at).slice(0, 16) : '',
        allowed_extensions: Array.isArray(request.allowed_extensions) ? request.allowed_extensions.join(', ') : request.allowed_extensions || '',
        max_file_size_mb: request.max_file_size_mb || '',
        max_files: request.max_files || 1,
        requires_verification: request.requires_verification !== false,
        allow_file_reuse: request.allow_file_reuse !== false,
        close_after_deadline: Boolean(request.close_after_deadline),
    };
}

function normalizeTargetPayload(request) {
    if (!request) return null;
    return {
        target_role: request.target_role || 'mahasiswa',
        scope_type: request.scope_type || 'filter',
        target_filters: request.target_filters || {},
        target_identifiers: request.target_identifiers || [],
    };
}

function canSubmitTarget(payload) {
    if (!payload?.target_role || !payload?.scope_type) return false;
    if (payload.scope_type === 'specific') return (payload.target_identifiers || []).length > 0;
    return true;
}

const emptyPreview = { total_valid: 0, total_invalid: 0, total_targets: 0, valid_targets: [], invalid_targets: [] };

export default function AdminRequests() {
    const navigate = useNavigate();
    const [rows, setRows] = useState([]);
    const [meta, setMeta] = useState(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState('');
    const [draftFilters, setDraftFilters] = useState({ search: '', status: '', target_role: '' });
    const [filters, setFilters] = useState(draftFilters);
    const requestRef = useRef(0);
    const [dialogOpen, setDialogOpen] = useState(false);
    const [editingRequest, setEditingRequest] = useState(null);
    const [form, setForm] = useState(emptyForm);
    const [targetPayload, setTargetPayload] = useState(null);
    const [saving, setSaving] = useState(false);
    const [preview, setPreview] = useState(null);
    const [previewLoading, setPreviewLoading] = useState(false);

    const fetchRequests = async (nextFilters = filters) => {
        const loadId = ++requestRef.current;
        setLoading(true);
        setError('');
        try {
            const response = await arsipApi.adminRequests({
                search: nextFilters.search,
                status: nextFilters.status,
                target_role: nextFilters.target_role,
            });
            const unwrapped = unwrapList(response);
            if (loadId !== requestRef.current) return;
            setRows(unwrapped.data);
            setMeta(unwrapped.meta);
        } catch (err) {
            if (loadId !== requestRef.current) return;
            const formatted = await formatArsipError(err);
            setError(formatted.message);
            customSwal.toast.error({ message: formatted.message });
        } finally {
            if (loadId === requestRef.current) setLoading(false);
        }
    };

    useEffect(() => {
        fetchRequests();
    }, []);

    const handleFilterChange = (key, value) => {
        setDraftFilters((prev) => ({ ...prev, [key]: value }));
    };

    const applyFilters = () => {
        setFilters(draftFilters);
        fetchRequests(draftFilters);
    };

    const openCreate = () => {
        setEditingRequest(null);
        setForm(emptyForm);
        setTargetPayload(null);
        setPreview(null);
        setDialogOpen(true);
    };

    const openEdit = (request) => {
        setEditingRequest(request);
        setForm(normalizeForm(request));
        setTargetPayload(normalizeTargetPayload(request));
        setPreview(null);
        setDialogOpen(true);
    };

    const buildSubmitPayload = () => {
        const payload = {
            title: form.title,
            description: form.description || null,
            deadline_at: form.deadline_at || null,
            max_files: Number(form.max_files || 1),
            max_file_size_mb: form.max_file_size_mb ? Number(form.max_file_size_mb) : null,
            allowed_extensions: lines(form.allowed_extensions),
            requires_verification: Boolean(form.requires_verification),
            allow_file_reuse: Boolean(form.allow_file_reuse),
            close_after_deadline: Boolean(form.close_after_deadline),
            ...targetPayload,
        };
        return payload;
    };

    const handlePreview = async () => {
        if (!canSubmitTarget(targetPayload)) {
            setPreview(emptyPreview);
            return;
        }
        setPreviewLoading(true);
        try {
            const response = await arsipApi.previewRequestTargets(buildSubmitPayload());
            setPreview(unwrapPreview(response));
        } catch (err) {
            const formatted = await formatArsipError(err);
            customSwal.toast.error({ message: formatted.message });
        } finally {
            setPreviewLoading(false);
        }
    };

    const removeTargetIdentifier = (identifier) => {
        const nextIdentifiers = (targetPayload?.target_identifiers || []).filter((item) => String(item) !== String(identifier));
        setTargetPayload({ ...targetPayload, scope_type: 'specific', target_identifiers: nextIdentifiers });
        setPreview((current) => {
            if (!current) return current;
            const validTargets = (current.valid_targets || []).filter((target) => String(target.identifier) !== String(identifier));
            const invalidTargets = (current.invalid_targets || []).filter((target) => String(target.identifier) !== String(identifier));
            return {
                ...current,
                total_valid: validTargets.length,
                total_invalid: invalidTargets.length,
                total_targets: validTargets.length + invalidTargets.length,
                valid_targets: validTargets,
                invalid_targets: invalidTargets,
            };
        });
    };

    const handleSubmit = async () => {
        if (!form.title.trim()) {
            customSwal.toast.error({ message: 'Judul wajib diisi.' });
            return;
        }
        if (!canSubmitTarget(targetPayload)) {
            customSwal.toast.error({ message: 'Pilih target terlebih dahulu.' });
            return;
        }
        setSaving(true);
        try {
            const payload = buildSubmitPayload();
            if (editingRequest) {
                await arsipApi.updateRequest(requestId(editingRequest), payload);
                customSwal.toast.success({ message: 'Draft request berhasil diperbarui.' });
            } else {
                await arsipApi.createRequest(payload);
                customSwal.toast.success({ message: 'Draft request berhasil dibuat.' });
            }
            setDialogOpen(false);
            await fetchRequests();
        } catch (err) {
            const formatted = await formatArsipError(err);
            customSwal.toast.error({ message: formatted.message });
        } finally {
            setSaving(false);
        }
    };

    const runLifecycle = async (request, action, title, text, success) => {
        if (!(await confirmAction({ title, text }))) return;
        try {
            await action(requestId(request));
            customSwal.toast.success({ message: success });
            await fetchRequests();
        } catch (err) {
            const formatted = await formatArsipError(err);
            customSwal.toast.error({ message: formatted.message });
        }
    };

    const previewTargets = preview ? [
        ...(preview.invalid_targets || []).map((target) => ({ ...target, valid: false })),
        ...(preview.valid_targets || []).map((target) => ({ ...target, valid: true })),
    ] : [];
    const visiblePreviewTargets = previewTargets.slice(0, 200);
    const canRemovePreviewTarget = targetPayload?.scope_type === 'specific';

    const deleteRequest = async (request) => {
        if (!(await confirmAction({ title: 'Hapus request?', text: 'Request akan dihapus permanen.', confirmText: 'Hapus', icon: 'warning' }))) return;
        try {
            await arsipApi.deleteRequest(requestId(request));
            customSwal.toast.success({ message: 'Request berhasil dihapus.' });
            await fetchRequests();
        } catch (err) {
            const formatted = await formatArsipError(err);
            customSwal.toast.error({ message: formatted.message });
        }
    };

    const columns = [
        { field: 'title', headerName: 'Judul', flex: 1, minWidth: 220, renderCell: (params) => <button type="button" className="text-blue-600 font-semibold hover:underline text-left" onClick={() => navigate(`/home/permintaan/${requestId(params.row)}`)}>{params.row.title || '-'}</button> },
        { field: 'status', headerName: 'Status', width: 130, renderCell: (params) => <StatusChip status={params.row.status} /> },
        { field: 'target_role', headerName: 'Target Role', width: 130, valueGetter: (value, row) => row.target_role || '-' },
        { field: 'deadline_at', headerName: 'Deadline', width: 170, renderCell: (params) => dateTime(params.row.deadline_at) },
        { field: 'progress', headerName: 'Progress', width: 160, sortable: false, renderCell: (params) => requestProgress(params.row) },
        { field: 'created_at', headerName: 'Dibuat', width: 170, renderCell: (params) => dateTime(params.row.created_at) },
        {
            field: 'actions',
            headerName: 'Aksi',
            width: 340,
            sortable: false,
            filterable: false,
            renderCell: (params) => {
                const request = params.row;
                return (
                    <div className="flex gap-1 flex-wrap">
                        <Button size="small" variant="outlined" component={Link} to={`/home/permintaan/${requestId(request)}`} sx={{ ...buttonSx, minWidth: 0, borderColor: '#e4e4e7', color: '#3f3f46' }}><VisibilityOutlined sx={{ fontSize: 17 }} /></Button>
                        {request.status === 'draft' && <Button size="small" onClick={() => openEdit(request)} sx={buttonSx}>Edit</Button>}
                        {request.status === 'draft' && <Button size="small" onClick={() => runLifecycle(request, arsipApi.publishRequest, 'Publish request?', 'Assignment akan dibuat untuk target request ini.', 'Request berhasil dipublish.')} sx={buttonSx}>Publish</Button>}
                        {request.status === 'published' && <Button size="small" onClick={() => runLifecycle(request, arsipApi.closeRequest, 'Tutup request?', 'Penerima tidak bisa upload file baru.', 'Request berhasil ditutup.')} sx={buttonSx}>Tutup</Button>}
                        {request.status === 'closed' && <Button size="small" onClick={() => runLifecycle(request, arsipApi.reopenRequest, 'Buka lagi request?', 'Request akan aktif kembali.', 'Request berhasil dibuka lagi.')} sx={buttonSx}>Reopen</Button>}
                        {['draft', 'closed'].includes(request.status) && <Button size="small" color="warning" onClick={() => runLifecycle(request, arsipApi.archiveRequest, 'Arsipkan request?', 'Request akan menjadi read-only.', 'Request berhasil diarsipkan.')} sx={buttonSx}>Arsip</Button>}
                        {request.status === 'draft' && <Button size="small" color="error" onClick={() => deleteRequest(request)} sx={buttonSx}>Hapus</Button>}
                    </div>
                );
            },
        },
    ];

    return (
        <div className="font-jakarta">
            <PageHeader
                title="Permintaan Berkas"
                subtitle="Kelola request, target penerima, dan lifecycle permintaan berkas."
                actions={
                    <Button variant="contained" startIcon={<AddOutlined />} onClick={openCreate} sx={{ ...buttonSx, backgroundColor: '#2563eb' }}>
                        Buat Request
                    </Button>
                }
            />

            {error && <Alert severity="error" sx={{ mb: 2, borderRadius: '0.5rem' }}>{error}</Alert>}

            <div className="bg-white rounded-lg border border-zinc-200 p-4 mb-4 flex flex-wrap gap-3">
                <TextField size="small" placeholder="Cari request..." value={draftFilters.search} onChange={(event) => handleFilterChange('search', event.target.value)} InputProps={{ startAdornment: <SearchOutlined sx={{ color: '#a1a1aa', mr: 1, fontSize: 18 }} /> }} sx={{ minWidth: 240 }} />
                <TextField size="small" select label="Status" value={draftFilters.status} onChange={(event) => handleFilterChange('status', event.target.value)} sx={{ minWidth: 160 }}>
                    <MenuItem value="">Semua</MenuItem>
                    <MenuItem value="draft">Draft</MenuItem>
                    <MenuItem value="published">Published</MenuItem>
                    <MenuItem value="closed">Closed</MenuItem>
                    <MenuItem value="archived">Archived</MenuItem>
                </TextField>
                <TextField size="small" select label="Target" value={draftFilters.target_role} onChange={(event) => handleFilterChange('target_role', event.target.value)} sx={{ minWidth: 160 }}>
                    <MenuItem value="">Semua</MenuItem>
                    <MenuItem value="mahasiswa">Mahasiswa</MenuItem>
                    <MenuItem value="dosen">Dosen</MenuItem>
                </TextField>
                <Button variant="contained" startIcon={<SearchOutlined />} onClick={applyFilters} sx={{ ...buttonSx, backgroundColor: '#2563eb' }}>Terapkan Filter</Button>
                <Button variant="outlined" startIcon={<RefreshOutlined />} onClick={() => fetchRequests()} sx={{ ...buttonSx, borderColor: '#e4e4e7', color: '#3f3f46' }}>Refresh</Button>
            </div>


            <div className="bg-white rounded-lg border border-zinc-200">
                <CustomDataTable
                    rows={rows}
                    columns={columns}
                    loading={loading}
                    getRowId={(row) => requestId(row)}
                    pageSize={50}
                    pageSizeOptions={[50]}
                />
            </div>

            <Dialog open={dialogOpen} onClose={() => setDialogOpen(false)} fullWidth maxWidth="lg">
                <DialogTitle className="!font-jakarta">{editingRequest ? 'Edit Draft Request' : 'Buat Request'}</DialogTitle>
                <DialogContent dividers className="space-y-4">
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                        <TextField size="small" label="Judul" value={form.title} onChange={(event) => setForm((prev) => ({ ...prev, title: event.target.value }))} required />
                        <TextField size="small" type="datetime-local" label="Deadline" value={form.deadline_at} onChange={(event) => setForm((prev) => ({ ...prev, deadline_at: event.target.value }))} InputLabelProps={{ shrink: true }} />
                        <TextField size="small" type="number" label="Maks file" value={form.max_files} onChange={(event) => setForm((prev) => ({ ...prev, max_files: event.target.value }))} />
                        <TextField size="small" type="number" label="Maks ukuran MB" value={form.max_file_size_mb} onChange={(event) => setForm((prev) => ({ ...prev, max_file_size_mb: event.target.value }))} />
                        <TextField size="small" label="Ekstensi diizinkan" value={form.allowed_extensions} onChange={(event) => setForm((prev) => ({ ...prev, allowed_extensions: event.target.value }))} helperText="Pisahkan dengan koma/baris." />
                        <TextField className="md:col-span-2" size="small" multiline minRows={3} label="Deskripsi / Instruksi" value={form.description} onChange={(event) => setForm((prev) => ({ ...prev, description: event.target.value }))} />
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-3 gap-2 text-xs text-zinc-600">
                        <label><input type="checkbox" checked={form.requires_verification} onChange={(event) => setForm((prev) => ({ ...prev, requires_verification: event.target.checked }))} /> Perlu verifikasi admin</label>
                        <label><input type="checkbox" checked={form.allow_file_reuse} onChange={(event) => setForm((prev) => ({ ...prev, allow_file_reuse: event.target.checked }))} /> Izinkan reuse file</label>
                        <label><input type="checkbox" checked={form.close_after_deadline} onChange={(event) => setForm((prev) => ({ ...prev, close_after_deadline: event.target.checked }))} /> Tutup setelah deadline</label>
                    </div>

                    <TargetPicker value={targetPayload} onChange={setTargetPayload} initialRole={targetPayload?.target_role || 'mahasiswa'} invalidTargets={preview?.invalid_targets || []} />

                    <div className="rounded-lg border border-zinc-200 bg-zinc-50 p-3 flex items-center justify-between gap-3 flex-wrap">
                        <div className="text-xs text-zinc-600">
                            <strong>Preview target</strong>
                            <p>{preview ? `${preview.total_valid ?? 0} valid · ${preview.total_invalid ?? 0} invalid · ${preview.total_targets ?? 0} total` : 'Belum divalidasi.'}</p>
                        </div>
                        <Button variant="outlined" disabled={previewLoading} onClick={handlePreview} sx={{ ...buttonSx, borderColor: '#e4e4e7', color: '#3f3f46' }}>{previewLoading ? 'Memvalidasi...' : 'Preview Target'}</Button>
                    </div>

                    {previewTargets.length > 0 && (
                        <div className="rounded-lg border border-zinc-200 bg-white p-3 text-xs text-zinc-700">
                            <strong>Daftar preview target</strong>
                            {previewTargets.length > visiblePreviewTargets.length && <p className="mt-1 text-zinc-500">Menampilkan {visiblePreviewTargets.length} dari {previewTargets.length} target.</p>}
                            <div className="mt-2 max-h-48 overflow-y-auto divide-y divide-zinc-100">
                                {visiblePreviewTargets.map((target) => (
                                    <div key={`${target.valid ? 'valid' : 'invalid'}-${target.identifier}`} className={`flex items-center justify-between gap-3 py-2 ${target.valid ? '' : 'text-red-700'}`}>
                                        <span><b>{target.identifier}</b> · {target.name_snapshot || target.name || target.reason || 'Valid'}</span>
                                        {canRemovePreviewTarget && <Button size="small" color="error" onClick={() => removeTargetIdentifier(target.identifier)} sx={buttonSx}>Batalkan</Button>}
                                    </div>
                                ))}
                            </div>
                        </div>
                    )}
                </DialogContent>
                <DialogActions>
                    <Button onClick={() => setDialogOpen(false)} sx={buttonSx}>Batal</Button>
                    <Button variant="contained" disabled={saving} onClick={handleSubmit} sx={{ ...buttonSx, backgroundColor: '#2563eb' }}>{saving ? 'Menyimpan...' : 'Simpan Draft'}</Button>
                </DialogActions>
            </Dialog>
        </div>
    );
}

// resources/js/views/admin/AdminRequests.vue
<template>
    <section class="page-stack">
        <PageHeader eyebrow="Permintaan berkas" title="Buat permintaan berkas" description="Atur detail request, pilih target penerima, preview target valid, lalu publish ketika sudah siap.">
            <template #actions><button type="button" class="secondary-btn" :disabled="loading" @click="loadAll">Refresh daftar</button></template>
        </PageHeader>

        <section class="panel-block">
            <div class="section-heading">
                <div>
                    <h2>Detail request</h2>
                    <p>Instruksi dan batas unggahan yang akan dilihat penerima.</p>
                </div>
            </div>
            <form id="request-create-form" class="form-grid" @submit.prevent="saveRequest">
                <label>Judul<input v-model="form.title" required placeholder="Contoh: Akta Kelahiran Angkatan 2022" /></label>
                <label>Maks file<input v-model.number="form.max_files" type="number" min="1" /></label>
                <label>Maks ukuran MB<input v-model.number="form.max_file_size_mb" type="number" min="1" placeholder="Default setting" /></label>
                <label>Deadline<input v-model="form.deadline_at" type="datetime-local" /></label>
                <fieldset class="wide extension-picker">
                    <legend>Ekstensi yang diizinkan</legend>
                    <p>Mahasiswa/dosen hanya bisa mengunggah file dengan format yang dipilih.</p>
                    <div class="extension-grid">
                        <label v-for="extension in extensionOptions" :key="extension" class="extension-check">
                            <input v-model="selectedExtensions" type="checkbox" :value="extension" />
                            <span>.{{ extension }}</span>
                        </label>
                    </div>
                </fieldset>
                <label class="wide">Deskripsi<textarea v-model="form.description" rows="3" placeholder="Instruksi untuk mahasiswa/dosen" /></label>
                <label class="check"><input v-model="form.requires_verification" type="checkbox" /> Perlu verifikasi admin</label>
                <label class="check"><input v-model="form.allow_file_reuse" type="checkbox" /> Izinkan reuse file lama</label>
                <label class="check"><input v-model="form.close_after_deadline" type="checkbox" /> Tutup setelah deadline</label>
            </form>
        </section>

        <TargetPicker @change="targeting = $event" />

        <section class="panel-block preview-panel">
            <div class="section-heading">
                <div>
                    <h2>Daftar target final</h2>
                    <p>{{ targeting?.summary || 'Target belum dihitung' }}</p>
                </div>
                <button type="button" class="secondary-btn" :disabled="previewLoading || !targeting?.canSubmit" @click="previewTargets">{{ previewLoading ? 'Memvalidasi...' : 'Validasi target' }}</button>
            </div>
            <AsyncState :loading="previewLoading" :error="previewError" :empty="!preview" empty-title="Belum ada daftar target" empty-text="Pilih target penerima, lalu klik Validasi target untuk melihat daftar final yang akan menerima request.">
                <div class="metric-grid compact">
                    <article class="metric-card"><span>Total</span><strong>{{ preview.total_targets ?? 0 }}</strong></article>
                    <article class="metric-card"><span>Valid</span><strong>{{ preview.total_valid ?? 0 }}</strong></article>
                    <article class="metric-card"><span>Invalid</span><strong>{{ preview.total_invalid ?? 0 }}</strong></article>
                </div>
                <div class="data-list preview-list">
                    <article v-for="target in preview.valid_targets || []" :key="target.identifier" class="list-row">
                        <div><strong>{{ target.identifier }}</strong><small>{{ target.name_snapshot || '-' }}</small></div>
                        <span class="status-pill ok">Valid</span>
                    </article>
                    <article v-for="target in preview.invalid_targets || []" :key="`invalid-${target.identifier}`" class="list-row">
                        <div><strong>{{ target.identifier }}</strong><small>{{ target.reason || 'Tidak valid' }}</small></div>
                        <span class="status-pill danger">Invalid</span>
                    </article>
                </div>
            </AsyncState>
        </section>

        <section class="panel-block publish-panel">
            <div class="section-heading">
                <div>
                    <h2>Simpan request</h2>
                    <p>{{ targeting?.summary || 'Pilih target penerima terlebih dahulu.' }}</p>
                </div>
                <div class="page-actions">
                    <button type="button" class="secondary-btn" :disabled="saving || previewLoading || !targeting?.canSubmit" @click="previewTargets">{{ previewLoading ? 'Memvalidasi...' : 'Validasi target' }}</button>
                    <button type="submit" form="request-create-form" :disabled="saving || previewLoading || !targeting?.canSubmit">{{ saving ? 'Menyimpan...' : 'Simpan draft' }}</button>
                </div>
            </div>
        </section>

        <section class="panel-block">
            <div class="section-heading"><h2>Daftar request</h2></div>
            <AsyncState :loading="loading" :error="error" :empty="requests.length === 0" empty-title="Belum ada request" empty-text="Draft request yang dibuat akan tampil di sini." @retry="loadAll">
                <div class="table-wrap">
                    <table>
                        <thead><tr><th>Request</th><th>Target</th><th>Status</th><th>Assignment</th><th>Aksi</th></tr></thead>
                        <tbody>
                            <tr v-for="request in requests" :key="request.request_id">
                                <td><strong>{{ request.title }}</strong><small>{{ request.description || '-' }}</small></td>
                                <td>{{ request.target_role }}<small>{{ request.scope_type }}</small></td>
                                <td><StatusPill :status="request.status" /></td>
                                <td>{{ request.assignments_count ?? 0 }}</td>
                                <td class="action-cell">
                                    <button v-if="request.status === 'draft'" type="button" class="secondary-btn" :disabled="publishingId === request.request_id" @click="publish(request)">{{ publishingId === request.request_id ? 'Publishing...' : 'Publish' }}</button>
                                    <RouterLink class="text-link" :to="{ name: 'admin.requests.show', params: { request_id: request.request_id } }">Detail</RouterLink>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </AsyncState>
        </section>
    </section>
</template>

<script setup>
import { onMounted, reactive, ref } from 'vue';
import { RouterLink } from 'vue-router';
import AsyncState from '../../components/AsyncState.vue';
import PageHeader from '../../components/PageHeader.vue';
import StatusPill from '../../components/StatusPill.vue';
import TargetPicker from '../../components/TargetPicker.vue';
import { arsipApi } from '../../services/arsipApi';
import { confirmAction } from '../../services/dialogs';
import { toErrorMessage } from '../../services/http';
import { useAppStore } from '../../stores/appStore';

const app = useAppStore();
const loading = ref(false);
const saving = ref(false);
const previewLoading = ref(false);
const publishingId = ref(null);
const error = ref('');
const previewError = ref('');
const requests = ref([]);
const preview = ref(null);
const targeting = ref(null);
const extensionOptions = ['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx', 'xls', 'xlsx'];
const selectedExtensions = ref(['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx', 'xls', 'xlsx']);

const form = reactive({
    title: '', description: '', max_files: 1, max_file_size_mb: null, deadline_at: '',
    requires_verification: true, allow_file_reuse: true, allow_inactive_upload: false, close_after_deadline: false,
});

function payload() {
    return {
        ...form,
        ...targeting.value.payload,
        deadline_at: form.deadline_at || null,
        max_file_size_mb: form.max_file_size_mb || null,
        allowed_extensions: selectedExtensions.value,
    };
}

async function loadAll() {
    loading.value = true;
    error.value = '';
    try {
        const data = await arsipApi.adminRequests();
        requests.value = data.requests || [];
    } catch (err) {
        error.value = toErrorMessage(err);
    } finally {
        loading.value = false;
    }
}

async function saveRequest() {
    if (!form.title?.trim()) {
        app.notify('error', 'Judul request wajib diisi.');
        return;
    }
    if (!targeting.value?.canSubmit) {
        app.notify('error', 'Pilih target penerima terlebih dahulu.');
        return;
    }
    if (selectedExtensions.value.length === 0) {
        app.notify('error', 'Pilih minimal satu ekstensi yang diizinkan.');
        return;
    }

    const confirmed = await confirmAction({
        title: 'Simpan draft request?',
        text: `Target: ${targeting.value.summary}. Draft masih bisa dicek sebelum dipublish.`,
        confirmText: 'Simpan draft',
    });
    if (!confirmed) return;

    saving.value = true;
    try {
        await arsipApi.createRequest(payload());
        app.notify('success', 'Request berhasil disimpan sebagai draft.');
        form.title = '';
        form.description = '';
        preview.value = null;
        await loadAll();
    } catch (err) {
        app.notify('error', toErrorMessage(err));
    } finally {
        saving.value = false;
    }
}

async function previewTargets() {
    if (!targeting.value?.canSubmit) {
        previewError.value = 'Pilih target penerima terlebih dahulu.';
        return;
    }

    previewLoading.value = true;
    previewError.value = '';
    try {
        const data = await arsipApi.previewRequestTargets(payload());
        preview.value = data.preview;
    } catch (err) {
        previewError.value = toErrorMessage(err);
    } finally {
        previewLoading.value = false;
    }
}

async function publish(request) {
    const confirmed = await confirmAction({
        title: 'Publish request?',
        text: 'Assignment akan dibuat untuk target request ini dan mulai terlihat oleh penerima.',
        confirmText: 'Publish',
        icon: 'warning',
    });
    if (!confirmed) return;

    publishingId.value = request.request_id;
    try {
        await arsipApi.publishRequest(request.request_id);
        app.notify('success', 'Request berhasil dipublish.');
        await loadAll();
    } catch (err) {
        app.notify('error', toErrorMessage(err));
    } finally {
        publishingId.value = null;
    }
}

onMounted(loadAll);
</script>
