// resources/js/components/TargetPicker.vue
<template>
    <section class="panel-block target-picker">
        <div class="section-heading target-heading">
            <div>
                <h2>Target penerima</h2>
                <p>Pilih kelompok besar dari filter, atau centang penerima tertentu jika hanya sebagian yang perlu diproses.</p>
            </div>
            <div class="segmented-control" aria-label="Role target">
                <button type="button" :class="role === 'mahasiswa' ? 'active' : ''" :disabled="props.lockRole" @click="setRole('mahasiswa')">Mahasiswa</button>
                <button type="button" :class="role === 'dosen' ? 'active' : ''" :disabled="props.lockRole" @click="setRole('dosen')">Dosen</button>
            </div>
        </div>

        <form class="target-filter-bar" @submit.prevent="loadTargets(1)">
            <label class="wide-search">Cari target
                <input v-model="filters.search" :placeholder="role === 'mahasiswa' ? 'Nama atau NIM' : 'Nama atau kode dosen'" />
            </label>
            <label v-if="role === 'mahasiswa'">Angkatan
                <input v-model="filters.angkatan" inputmode="numeric" placeholder="Contoh: 2022" />
            </label>
            <label>Status
                <select v-model="filters.status">
                    <option value="A">Aktif</option>
                    <option value="C">Cuti</option>
                    <option value="TA">Tidak Aktif</option>
                    <option value="N">Tidak Aktif (N)</option>
                    <option value="">Semua status</option>
                </select>
            </label>
            <button type="submit" :disabled="targetLoading">{{ targetLoading ? 'Mencari...' : 'Terapkan filter' }}</button>
        </form>

        <div class="target-summary-strip">
            <div>
                <span>Mode aktif</span>
                <strong>{{ mode === 'filter' ? 'Semua hasil filter' : 'Pilih manual' }}</strong>
            </div>
            <div>
                <span>Data ditemukan</span>
                <strong>{{ effectiveTargetTotal }}</strong>
            </div>
            <div>
                <span>Target tersimpan</span>
                <strong>{{ mode === 'filter' ? filterSummary : `${selectedIdentifiers.length} penerima` }}</strong>
            </div>
        </div>

        <AsyncState :loading="targetLoading" :error="targetError" :empty="targets.length === 0" empty-title="Belum ada target" empty-text="Ubah filter untuk mencari mahasiswa atau dosen." @retry="loadTargets(filters.page)">
            <div class="bulk-actions">
                <strong>{{ mode === 'filter' ? 'Filter ini akan disimpan sebagai target' : `${selectedIdentifiers.length} target dipilih` }}</strong>
                <button type="button" class="secondary-btn" :disabled="targetLoading || selectingAllFiltered || effectiveTargetTotal === 0" @click="selectFilteredTargets">
                    {{ selectingAllFiltered ? 'Memilih target...' : `Pilih semua hasil filter (${effectiveTargetTotal})` }}
                </button>
                <button type="button" class="secondary-btn" :disabled="targetLoading || pageSelectableIdentifiers.length === 0" @click="selectPageTargets">Pilih halaman ini</button>
                <button type="button" class="ghost-btn" :disabled="targetLoading || selectedIdentifiers.length === 0" @click="clearTargets">Kosongkan pilihan</button>
            </div>

            <div class="table-wrap target-table-wrap">
                <table>
                    <thead>
                        <tr>
                            <th><input type="checkbox" :checked="allPageSelected" :disabled="targetLoading || pageSelectableIdentifiers.length === 0" aria-label="Pilih semua target di halaman ini" @change="togglePageTargets($event)" /></th>
                            <th>Identifier</th>
                            <th>Nama</th>
                            <th v-if="role === 'mahasiswa'">Angkatan</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr v-for="target in targets" :key="target.identifier" :class="selectedIdentifiers.includes(target.identifier) ? 'selected-row' : ''">
                            <td><input type="checkbox" :value="target.identifier" :disabled="targetLoading || !target.has_account" :aria-label="`Pilih target ${target.identifier}`" v-model="selectedIdentifiers" @change="setMode('specific')" /></td>
                            <td><strong>{{ target.identifier }}</strong></td>
                            <td>{{ target.name || '-' }}</td>
                            <td v-if="role === 'mahasiswa'">{{ target.angkatan || '-' }}</td>
                            <td>{{ target.status || '-' }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>

            <div class="pagination-row">
                <button type="button" class="secondary-btn" :disabled="targetLoading || targetMeta.current_page <= 1" @click="changeTargetPage(targetMeta.current_page - 1)">Sebelumnya</button>
                <span>Halaman {{ targetMeta.current_page || 1 }} dari {{ targetMeta.last_page || 1 }} · {{ effectiveTargetTotal }} data</span>
                <button type="button" class="secondary-btn" :disabled="targetLoading || targetMeta.current_page >= targetMeta.last_page" @click="changeTargetPage(targetMeta.current_page + 1)">Berikutnya</button>
            </div>
        </AsyncState>
    </section>
</template>

<script setup>
import { computed, onMounted, reactive, ref, watch } from 'vue';
import AsyncState from './AsyncState.vue';
import { arsipApi } from '../services/arsipApi';
import { toErrorMessage } from '../services/http';

const props = defineProps({
    initialRole: { type: String, default: 'mahasiswa' },
    lockRole: { type: Boolean, default: false },
});
const emit = defineEmits(['change']);

const role = ref(['mahasiswa', 'dosen'].includes(props.initialRole) ? props.initialRole : 'mahasiswa');
const mode = ref('filter');
const targets = ref([]);
const selectedIdentifiers = ref([]);
const targetLoading = ref(false);
const selectingAllFiltered = ref(false);
const targetError = ref('');
const targetMeta = ref({ current_page: 1, last_page: 1, per_page: 25, total: 0 });
const loadedTargetQueryKey = ref('');
const filters = reactive({ search: '', angkatan: '', status: 'A', page: 1 });

const filterSummary = computed(() => {
    const parts = [];
    if (role.value === 'mahasiswa' && csv(filters.angkatan).length) parts.push(`angkatan ${csv(filters.angkatan).join(', ')}`);
    if (csv(filters.status).length) parts.push(`status ${csv(filters.status).join(', ')}`);
    return parts.length ? parts.join(' · ') : `semua ${roleLabel.value}`;
});

const roleLabel = computed(() => (role.value === 'mahasiswa' ? 'mahasiswa' : 'dosen'));

const payload = computed(() => ({
    target_role: role.value,
    scope_type: mode.value === 'filter' ? 'filter' : 'specific',
    target_filters: mode.value === 'filter' ? filterPayload() : {},
    target_identifiers: mode.value === 'specific' ? selectedIdentifiers.value : [],
}));

const pageSelectableIdentifiers = computed(() => targets.value.filter((target) => target.has_account).map((target) => target.identifier));
const allPageSelected = computed(() => pageSelectableIdentifiers.value.length > 0
    && pageSelectableIdentifiers.value.every((identifier) => selectedIdentifiers.value.includes(identifier)));
const isCurrentFilterLoaded = computed(() => loadedTargetQueryKey.value === targetQueryKey());
const effectiveTargetTotal = computed(() => (isCurrentFilterLoaded.value ? targetMeta.value.total || 0 : 0));
const canSubmit = computed(() => mode.value === 'filter' ? effectiveTargetTotal.value > 0 : selectedIdentifiers.value.length > 0);

function csv(value) {
    return String(value || '')
        .split(',')
        .map((item) => item.trim())
        .filter(Boolean);
}

function filterPayload() {
    const payload = {};
    const angkatan = csv(filters.angkatan);
    const status = csv(filters.status).map((item) => item.toUpperCase());

    if (role.value === 'mahasiswa' && angkatan.length) payload.angkatan = angkatan;
    if (status.length) payload.student_status = status;
    payload.has_account = true;

    return payload;
}

function targetQuery(page = filters.page, perPage = 25) {
    return {
        role: role.value,
        search: filters.search,
        angkatan: role.value === 'mahasiswa' ? csv(filters.angkatan)[0] || '' : '',
        status: csv(filters.status)[0] || '',
        has_account: '1',
        per_page: perPage,
        page,
    };
}

function targetQueryKey(page = filters.page) {
    const query = targetQuery(page);
    return JSON.stringify({
        role: query.role,
        search: query.search,
        angkatan: query.angkatan,
        status: query.status,
        has_account: query.has_account,
        page: query.page,
    });
}

function resetLoadedTargets() {
    loadedTargetQueryKey.value = '';
    targetMeta.value = { current_page: 1, last_page: 1, per_page: 25, total: 0 };
    targets.value = [];
}

function notifyChange() {
    emit('change', {
        payload: payload.value,
        role: role.value,
        mode: mode.value,
        selectedCount: selectedIdentifiers.value.length,
        canSubmit: canSubmit.value,
        summary: mode.value === 'filter' ? filterSummary.value : `${selectedIdentifiers.value.length} penerima`,
    });
}

function setRole(nextRole) {
    if (role.value === nextRole) return;
    role.value = nextRole;
    selectedIdentifiers.value = [];
    filters.angkatan = '';
    filters.page = 1;
    resetLoadedTargets();
    loadTargets(1);
}

function setMode(nextMode) {
    mode.value = nextMode;
}

async function loadTargets(page = 1) {
    targetLoading.value = true;
    targetError.value = '';
    filters.page = page;
    const query = targetQuery(page);
    const queryKey = targetQueryKey(page);
    try {
        const data = await arsipApi.adminTargets(query);
        if (queryKey !== targetQueryKey(page)) return;
        targets.value = data.targets || [];
        targetMeta.value = data.meta || { current_page: 1, last_page: 1, per_page: 25, total: 0 };
        loadedTargetQueryKey.value = queryKey;
    } catch (err) {
        loadedTargetQueryKey.value = '';
        targetMeta.value = { current_page: page, last_page: 1, per_page: 25, total: 0 };
        targets.value = [];
        targetError.value = toErrorMessage(err);
    } finally {
        targetLoading.value = false;
        notifyChange();
    }
}

function mergeIdentifiers(identifiers) {
    const merged = new Set(selectedIdentifiers.value);
    identifiers.forEach((identifier) => merged.add(identifier));
    selectedIdentifiers.value = Array.from(merged);
}

function selectPageTargets() {
    mode.value = 'specific';
    mergeIdentifiers(pageSelectableIdentifiers.value);
}

function togglePageTargets(event) {
    mode.value = 'specific';
    if (event.target.checked) {
        mergeIdentifiers(pageSelectableIdentifiers.value);
        return;
    }

    const pageSet = new Set(pageSelectableIdentifiers.value);
    selectedIdentifiers.value = selectedIdentifiers.value.filter((identifier) => !pageSet.has(identifier));
}

async function selectFilteredTargets() {
    if (effectiveTargetTotal.value === 0) return;

    mode.value = 'specific';
    selectingAllFiltered.value = true;
    targetError.value = '';

    try {
        const identifiers = [];
        let page = 1;
        let lastPage = 1;

        do {
            const data = await arsipApi.adminTargets(targetQuery(page, 100));
            identifiers.push(...(data.targets || []).filter((target) => target.has_account).map((target) => target.identifier));
            lastPage = data.meta?.last_page || 1;
            page += 1;
        } while (page <= lastPage);

        mergeIdentifiers(identifiers);
    } catch (err) {
        targetError.value = toErrorMessage(err);
    } finally {
        selectingAllFiltered.value = false;
    }
}

function clearTargets() {
    selectedIdentifiers.value = [];
    mode.value = 'filter';
}

function changeTargetPage(page) {
    loadTargets(page);
}

watch([() => filters.search, () => filters.angkatan, () => filters.status], () => {
    filters.page = 1;
    resetLoadedTargets();
    notifyChange();
});
watch([role, mode, selectedIdentifiers], notifyChange, { deep: true });
onMounted(() => { loadTargets(); notifyChange(); });
</script>

// resources/js/features/arsip-digital/components/TargetPicker.jsx
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { arsipApi } from '../../../libs/arsip_api';
import { formatArsipError } from '../../../libs/arsip_http';
import { useTargetPicker } from '../hooks/useTargetPicker';
import {
    Alert,
    Button,
    Checkbox,
    MenuItem,
    TextField,
} from '@mui/material';
import SearchOutlined from '@mui/icons-material/SearchOutlined';

const buttonSx = {
    borderRadius: '0.5rem',
    textTransform: 'none',
    fontFamily: 'Plus Jakarta Sans, sans-serif',
};

const defaultFilters = {
    search: '',
    angkatan: '',
    status: '',
    has_account: '',
    page: 1,
    per_page: 25,
};

function csv(value) {
    return String(value || '')
        .split(',')
        .map((item) => item.trim())
        .filter(Boolean);
}

function normalizeIdentifier(target) {
    return String(target?.identifier ?? target?.id ?? '').trim();
}

function unwrapTargets(response) {
    const data = response?.data ?? response ?? {};
    const direct = Array.isArray(data) ? data : null;
    const targets = direct ?? data.targets ?? data.data ?? [];
    return {
        data: Array.isArray(targets) ? targets : [],
        meta: data.meta ?? data.pagination ?? response?.meta ?? null,
    };
}

function metaTotal(meta) {
    return Number(meta?.total ?? meta?.count ?? meta?.total_targets ?? 0);
}

function normalizeInitialFilters(value, role) {
    const targetFilters = value?.target_filters || {};
    const studentStatus = csv(targetFilters.student_status || targetFilters.status);
    return {
        ...defaultFilters,
        angkatan: role === 'mahasiswa' ? csv(targetFilters.angkatan).join(', ') : '',
        status: studentStatus.join(', '),
        has_account: targetFilters.has_account === false ? '0' : targetFilters.has_account === true ? '1' : '',
    };
}

function targetQueryKey(filters) {
    return JSON.stringify(filters);
}

function buildPayload(role, mode, filters, selectedIdentifiers) {
    const targetFilters = {};

    if (mode === 'filter') {
        const angkatan = csv(filters.angkatan);
        const status = csv(filters.status).map((item) => item.toUpperCase());

        if (role === 'mahasiswa' && angkatan.length) targetFilters.angkatan = angkatan;
        if (status.length) targetFilters.student_status = status;
        if (filters.has_account === '1') targetFilters.has_account = true;
        if (filters.has_account === '0') targetFilters.has_account = false;
    }

    return {
        target_role: role,
        scope_type: mode === 'specific' ? 'specific' : 'filter',
        target_filters: mode === 'filter' ? targetFilters : {},
        target_identifiers: mode === 'specific' ? selectedIdentifiers : [],
    };
}

export default function TargetPicker({ value, onChange, initialRole = 'mahasiswa', disabled = false }) {
    const [initialized, setInitialized] = useState(false);
    const roleRef = useRef(initialRole);

    const fetchTargets = useCallback(async (filters, page = filters?.page || 1) => {
        const role = roleRef.current || initialRole;
        const query = {
            role,
            search: filters.search,
            angkatan: role === 'mahasiswa' ? csv(filters.angkatan)[0] || '' : '',
            status: csv(filters.status)[0] || '',
            has_account: filters.has_account === '' ? undefined : filters.has_account === '1',
            page,
            per_page: filters.per_page || 25,
        };
        const response = await arsipApi.adminTargets(query);
        return unwrapTargets(response);
    }, [initialRole]);

    const picker = useTargetPicker({ fetchTargets });
    const {
        state,
        dispatch,
        setRole,
        setMode,
        setFilters,
        setTargets,
        setLoading,
        setError,
        toggleIdentifier,
        clearSelection,
        selectAllFiltered,
    } = picker;

    const role = state.role || initialRole || 'mahasiswa';
    roleRef.current = role;
    const filters = { ...defaultFilters, ...state.filters };
    const selectedIdentifiers = state.selectedIdentifiers;
    const currentPage = Number(state.targetMeta?.current_page ?? filters.page ?? 1);
    const lastPage = Number(state.targetMeta?.last_page ?? 1);
    const hasTargetMeta = Boolean(state.targetMeta);
    const total = hasTargetMeta ? metaTotal(state.targetMeta) : state.targets.length;
    const currentQueryKey = targetQueryKey(filters);
    const canSelectAllFiltered = currentQueryKey === state.loadedTargetQueryKey;
    const pageIdentifiers = state.targets.map(normalizeIdentifier).filter(Boolean);
    const selectablePageIdentifiers = pageIdentifiers;
    const allPageSelected = selectablePageIdentifiers.length > 0
        && selectablePageIdentifiers.every((identifier) => selectedIdentifiers.includes(identifier));

    const payload = useMemo(
        () => buildPayload(role, state.mode, filters, selectedIdentifiers),
        [role, state.mode, filters.search, filters.angkatan, filters.status, filters.has_account, selectedIdentifiers],
    );

    useEffect(() => {
        if (initialized) return;
        const nextRole = ['mahasiswa', 'dosen'].includes(value?.target_role) ? value.target_role : initialRole;
        setRole(nextRole);
        setMode(value?.scope_type === 'specific' ? 'specific' : 'filter');
        setFilters(normalizeInitialFilters(value, nextRole));
        if (Array.isArray(value?.target_identifiers)) {
            dispatch({ type: 'SELECT_ALL_FILTERED', payload: value.target_identifiers.map(String) });
        }
        setInitialized(true);
    }, [dispatch, initialRole, initialized, setFilters, setMode, setRole, value]);

    useEffect(() => {
        if (!initialized) return;
        onChange?.(payload);
    }, [initialized, onChange, payload]);

    const loadTargets = async (page = 1) => {
        setLoading(true);
        setError(null);
        const nextFilters = { ...filters, page };
        setFilters(nextFilters);
        try {
            const response = await arsipApi.adminTargets({
                role,
                search: nextFilters.search,
                angkatan: role === 'mahasiswa' ? csv(nextFilters.angkatan)[0] || '' : '',
                status: csv(nextFilters.status)[0] || '',
                has_account: nextFilters.has_account === '' ? undefined : nextFilters.has_account === '1',
                page,
                per_page: nextFilters.per_page,
            });
            const unwrapped = unwrapTargets(response);
            setTargets(unwrapped.data, unwrapped.meta, targetQueryKey(nextFilters));
        } catch (err) {
            const formatted = await formatArsipError(err);
            setError(formatted.message);
        }
    };

    useEffect(() => {
        if (initialized) loadTargets(1);
    }, [initialized, role]);

    const handleRoleChange = (nextRole) => {
        setRole(nextRole);
        setMode('filter');
        setFilters({ ...defaultFilters, angkatan: nextRole === 'mahasiswa' ? filters.angkatan : '' });
    };

    const handleFilterChange = (key, nextValue) => {
        setFilters({ ...filters, [key]: nextValue, page: 1 });
    };

    const togglePage = (checked) => {
        setMode('specific');
        if (checked) {
            const merged = Array.from(new Set([...selectedIdentifiers, ...selectablePageIdentifiers]));
            dispatch({ type: 'SELECT_ALL_FILTERED', payload: merged });
            return;
        }
        dispatch({ type: 'SELECT_ALL_FILTERED', payload: selectedIdentifiers.filter((identifier) => !pageIdentifiers.includes(identifier)) });
    };

    const handleToggleIdentifier = (identifier) => {
        setMode('specific');
        toggleIdentifier(identifier);
    };

    const handleClearSelection = () => {
        clearSelection();
        setMode('filter');
    };

    const handleSelectAllFiltered = async () => {
        if (!canSelectAllFiltered) return;
        setMode('specific');
        await selectAllFiltered({ filters, targets: state.targets, meta: state.targetMeta, expectedQueryKey: currentQueryKey });
    };

    return (
        <section className="bg-white rounded-lg border border-zinc-200 p-4">
            <div className="flex items-start justify-between gap-3 flex-wrap mb-4">
                <div>
                    <p className="text-xs font-semibold text-blue-600 uppercase tracking-wide">Target penerima</p>
                    <h3 className="text-sm font-semibold text-zinc-800 mt-1">Pilih target request</h3>
                    <p className="text-xs text-zinc-500 mt-1">Gunakan filter untuk target massal, atau centang baris untuk target spesifik.</p>
                </div>
                <div className="flex rounded-lg border border-zinc-200 overflow-hidden">
                    {['mahasiswa', 'dosen'].map((item) => (
                        <button
                            key={item}
                            type="button"
                            disabled={disabled}
                            onClick={() => handleRoleChange(item)}
                            className={`px-3 py-2 text-xs font-semibold capitalize ${role === item ? 'bg-blue-600 text-white' : 'bg-white text-zinc-600 hover:bg-zinc-50'}`}
                        >
                            {item}
                        </button>
                    ))}
                </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-5 gap-3 mb-4">
                <TextField size="small" label="Cari" value={filters.search} disabled={disabled} onChange={(event) => handleFilterChange('search', event.target.value)} InputProps={{ startAdornment: <SearchOutlined sx={{ color: '#a1a1aa', mr: 1, fontSize: 18 }} /> }} />
                {role === 'mahasiswa' && (
                    <TextField size="small" label="Angkatan" value={filters.angkatan} disabled={disabled} onChange={(event) => handleFilterChange('angkatan', event.target.value)} placeholder="2022, 2023" />
                )}
                <TextField size="small" label="Status" value={filters.status} disabled={disabled} onChange={(event) => handleFilterChange('status', event.target.value)} placeholder="A, C, TA" />
                <TextField size="small" select label="Akun" value={filters.has_account} disabled={disabled} onChange={(event) => handleFilterChange('has_account', event.target.value)}>
                    <MenuItem value="">Semua</MenuItem>
                    <MenuItem value="1">Punya akun</MenuItem>
                    <MenuItem value="0">Belum punya akun</MenuItem>
                </TextField>
                <Button variant="contained" disabled={disabled || state.loading} onClick={() => loadTargets(1)} sx={{ ...buttonSx, backgroundColor: '#2563eb' }}>
                    Terapkan Filter
                </Button>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-3 mb-4">
                <div className="rounded-lg bg-zinc-50 border border-zinc-200 p-3"><span className="text-xs text-zinc-500">Mode</span><strong className="block text-sm text-zinc-800 mt-1">{state.mode === 'specific' ? 'Target spesifik' : 'Filter'}</strong></div>
                <div className="rounded-lg bg-zinc-50 border border-zinc-200 p-3"><span className="text-xs text-zinc-500">Preview ditemukan</span><strong className="block text-sm text-zinc-800 mt-1">{total}</strong></div>
                <div className="rounded-lg bg-zinc-50 border border-zinc-200 p-3"><span className="text-xs text-zinc-500">Dipilih spesifik</span><strong className="block text-sm text-zinc-800 mt-1">{selectedIdentifiers.length}</strong></div>
            </div>

            {state.error && <Alert severity="error" sx={{ mb: 2, borderRadius: '0.5rem' }}>{String(state.error)}</Alert>}
            {!hasTargetMeta && state.targets.length > 0 && <Alert severity="info" sx={{ mb: 2, borderRadius: '0.5rem' }}>Backend pagination target belum tersedia. Pilih semua hanya memilih hasil filter yang sudah dimuat.</Alert>}
            {!canSelectAllFiltered && <p className="text-xs text-amber-600 mb-2">Terapkan filter sebelum pilih semua hasil.</p>}

            <div className="flex items-center justify-between gap-3 flex-wrap mb-3">
                <div className="text-xs text-zinc-500">Payload aktif: <strong className="text-zinc-700">{payload.scope_type}</strong> · {payload.target_role}</div>
                <div className="flex flex-wrap gap-2">
                    <Button size="small" variant="outlined" disabled={disabled || state.loading || state.selectingAllFiltered || total < 1 || !canSelectAllFiltered} onClick={handleSelectAllFiltered} sx={{ ...buttonSx, borderColor: '#e4e4e7', color: '#3f3f46' }}>
                        {state.selectingAllFiltered ? 'Memilih...' : hasTargetMeta ? `Pilih semua hasil filter (${total})` : `Pilih semua hasil dimuat (${state.targets.length})`}
                    </Button>
                    <Button size="small" variant="outlined" disabled={disabled || selectablePageIdentifiers.length < 1} onClick={() => togglePage(true)} sx={{ ...buttonSx, borderColor: '#e4e4e7', color: '#3f3f46' }}>
                        Pilih halaman ini
                    </Button>
                    <Button size="small" disabled={disabled || selectedIdentifiers.length < 1} onClick={handleClearSelection} sx={buttonSx}>
                        Kosongkan
                    </Button>
                </div>
            </div>

            <div className="overflow-x-auto rounded-lg border border-zinc-200">
                <table className="min-w-full text-sm">
                    <thead className="bg-zinc-50 text-xs uppercase text-zinc-500">
                        <tr>
                            <th className="w-10 px-3 py-2 text-left"><Checkbox size="small" checked={allPageSelected} disabled={disabled || selectablePageIdentifiers.length < 1} onChange={(event) => togglePage(event.target.checked)} /></th>
                            <th className="px-3 py-2 text-left">Identifier</th>
                            <th className="px-3 py-2 text-left">Nama</th>
                            {role === 'mahasiswa' && <th className="px-3 py-2 text-left">Angkatan</th>}
                            <th className="px-3 py-2 text-left">Status</th>
                            <th className="px-3 py-2 text-left">Akun</th>
                        </tr>
                    </thead>
                    <tbody className="divide-y divide-zinc-100">
                        {state.targets.map((target) => {
                            const identifier = normalizeIdentifier(target);
                            return (
                                <tr key={identifier} className={selectedIdentifiers.includes(identifier) ? 'bg-blue-50' : 'bg-white'}>
                                    <td className="px-3 py-2"><Checkbox size="small" checked={selectedIdentifiers.includes(identifier)} disabled={disabled} onChange={() => handleToggleIdentifier(identifier)} /></td>
                                    <td className="px-3 py-2 font-semibold text-zinc-800">{identifier || '-'}</td>
                                    <td className="px-3 py-2 text-zinc-700">{target.name || target.name_snapshot || '-'}</td>
                                    {role === 'mahasiswa' && <td className="px-3 py-2 text-zinc-700">{target.angkatan || target.angkatan_snapshot || '-'}</td>}
                                    <td className="px-3 py-2 text-zinc-700">{target.status || target.status_snapshot || '-'}</td>
                                    <td className="px-3 py-2 text-zinc-700">{target.has_account === false ? 'Tidak' : 'Ya'}</td>
                                </tr>
                            );
                        })}
                        {!state.loading && state.targets.length === 0 && (
                            <tr><td colSpan={role === 'mahasiswa' ? 6 : 5} className="px-3 py-8 text-center text-zinc-500">Belum ada target. Terapkan filter untuk memuat data.</td></tr>
                        )}
                    </tbody>
                </table>
            </div>

            <div className="flex items-center justify-between gap-3 flex-wrap mt-3 text-xs text-zinc-500">
                <span>{hasTargetMeta ? `Halaman ${currentPage} dari ${lastPage} · ${total} data` : `Data dimuat: ${state.targets.length}`}</span>
                <div className="flex gap-2">
                    <Button size="small" variant="outlined" disabled={disabled || state.loading || currentPage <= 1} onClick={() => loadTargets(currentPage - 1)} sx={{ ...buttonSx, borderColor: '#e4e4e7', color: '#3f3f46' }}>Sebelumnya</Button>
                    <Button size="small" variant="outlined" disabled={disabled || state.loading || currentPage >= lastPage} onClick={() => loadTargets(currentPage + 1)} sx={{ ...buttonSx, borderColor: '#e4e4e7', color: '#3f3f46' }}>Berikutnya</Button>
                </div>
            </div>
        </section>
    );
}
