// resources/js/views/admin/AdminDistributions.vue
<template>
    <section class="page-stack">
        <PageHeader eyebrow="Distribusi berkas" title="Kirim file ke penerima" description="Buat distribusi, pilih target penerima, publish, lalu upload file untuk masing-masing penerima.">
            <template #actions><button type="button" class="secondary-btn" @click="load">Refresh daftar</button></template>
        </PageHeader>

        <section class="panel-block">
            <div class="section-heading">
                <div>
                    <h2>Detail distribusi</h2>
                    <p>Judul dan catatan yang membantu admin mengenali batch pengiriman file.</p>
                </div>
            </div>
            <form class="form-grid" @submit.prevent="saveDistribution">
                <label>Judul<input v-model="form.title" required placeholder="Sertifikat Seminar AI 2026" /></label>
                <label class="wide">Deskripsi<textarea v-model="form.description" rows="3" placeholder="Catatan internal atau instruksi singkat" /></label>
            </form>
        </section>

        <TargetPicker @change="targeting = $event" />

        <section class="panel-block publish-panel">
            <div class="section-heading">
                <div>
                    <h2>Simpan distribusi</h2>
                    <p>{{ targeting?.summary || 'Pilih target penerima terlebih dahulu.' }}</p>
                </div>
                <div class="page-actions">
                    <button type="button" class="secondary-btn" :disabled="!targeting?.canSubmit" @click="previewTargets">Preview target</button>
                    <button type="button" :disabled="!targeting?.canSubmit" @click="saveDistribution">Simpan draft</button>
                </div>
            </div>
            <div class="target-preview-result">
                <AsyncState :loading="previewLoading" :error="previewError" :empty="!preview" empty-title="Belum ada preview" empty-text="Klik Preview target untuk memastikan penerima valid sebelum draft disimpan.">
                    <div class="metric-grid compact">
                        <article class="metric-card"><span>Total</span><strong>{{ preview.total_targets ?? 0 }}</strong></article>
                        <article class="metric-card"><span>Valid</span><strong>{{ preview.total_valid ?? 0 }}</strong></article>
                        <article class="metric-card"><span>Invalid</span><strong>{{ preview.total_invalid ?? 0 }}</strong></article>
                    </div>
                    <div class="data-list preview-list">
                        <article v-for="target in preview.valid_targets || []" :key="target.identifier" class="list-row"><div><strong>{{ target.identifier }}</strong><small>{{ target.name_snapshot || '-' }}</small></div><StatusPill status="approved" /></article>
                        <article v-for="target in preview.invalid_targets || []" :key="`invalid-${target.identifier}`" class="list-row"><div><strong>{{ target.identifier }}</strong><small>{{ target.reason || 'Tidak valid' }}</small></div><StatusPill status="rejected" /></article>
                    </div>
                </AsyncState>
            </div>
        </section>

        <section class="panel-block">
            <div class="section-heading"><h2>Daftar distribusi</h2></div>
            <AsyncState :loading="loading" :error="error" :empty="distributions.length === 0" empty-title="Belum ada distribusi" empty-text="Distribusi draft/published akan tampil di sini." @retry="load">
                <div class="table-wrap">
                    <table>
                        <thead><tr><th>Distribusi</th><th>Target</th><th>Status</th><th>Penerima</th><th>Aksi</th></tr></thead>
                        <tbody>
                            <tr v-for="item in distributions" :key="item.distribution_id" :class="selectedId === item.distribution_id ? 'selected-row' : ''">
                                <td><strong>{{ item.title }}</strong><small>{{ item.description || '-' }}</small></td>
                                <td>{{ item.target_role }}<small>{{ item.scope_type }}</small></td>
                                <td><StatusPill :status="item.status" /></td>
                                <td>{{ item.recipients_count ?? 0 }}</td>
                                <td class="action-cell">
                                    <button v-if="item.status === 'draft'" type="button" class="secondary-btn" @click="publish(item)">Publish</button>
                                    <button type="button" class="ghost-btn" @click="selectDistribution(item)">Penerima</button>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </AsyncState>
        </section>

        <section v-if="selectedId" class="panel-block">
            <div class="section-heading">
                <div>
                    <h2>Penerima distribusi #{{ selectedId }}</h2>
                    <p v-if="selectedDistribution">{{ selectedDistribution.title }} · {{ statusLabel(selectedDistribution.status) }}</p>
                </div>
                <button type="button" class="secondary-btn" @click="refreshSelectedDistribution">Refresh</button>
            </div>

            <div v-if="isSelectedDistributionPublished" class="page-stack">
                <section class="notice-box info">
                    <div>
                        <strong>Bulk upload ZIP</strong>
                        <p>Upload satu ZIP berisi file personal. Sistem mencocokkan file ke penerima dari identifier pada nama file, lalu menampilkan preview sebelum file disimpan.</p>
                        <ul class="bulk-upload-guide">
                            <li>Mahasiswa: nama file harus memuat NIM, contoh <code>22123456.pdf</code> atau <code>22123456 - Nama Mahasiswa.pdf</code>.</li>
                            <li>Dosen: nama file harus memuat kode dosen atau <code>kd_dosen</code>, contoh <code>RP.pdf</code>, <code>LA - SK Mengajar.pdf</code>, atau <code>dokumen_DV_2024.pdf</code>. Jangan pakai NIDN, email, atau nama dosen kecuali identifier sistem sudah diubah.</li>
                            <li>File boleh langsung di root ZIP atau di dalam subfolder. Hanya file dengan status <strong>File cocok</strong> yang akan disimpan saat dikonfirmasi.</li>
                        </ul>
                    </div>
                </section>

                <form class="form-grid" @submit.prevent="uploadBulkZip">
                    <label class="wide">File ZIP
                        <input ref="bulkFileInput" type="file" accept=".zip,application/zip,application/x-zip-compressed" :disabled="bulkUploading" @change="selectBulkZip" />
                    </label>
                    <div class="wide page-actions">
                        <button type="submit" :disabled="bulkUploading || !bulkZipFile">{{ bulkUploading ? 'Mengunggah...' : 'Upload ZIP & preview' }}</button>
                        <button type="button" class="secondary-btn" :disabled="bulkLoading || !bulkJob" @click="loadBulkJob(bulkJob.bulk_upload_job_id)">Refresh status</button>
                    </div>
                </form>

                <div v-if="bulkZipFile" class="notice-box info">
                    <div>
                        <strong>ZIP dipilih</strong>
                        <p>{{ bulkZipFile.name }} · {{ formatBytes(bulkZipFile.size) }}</p>
                    </div>
                </div>

                <div v-if="bulkError" class="notice-box error">
                    <div>
                        <strong>Bulk upload ZIP belum bisa diproses</strong>
                        <p>{{ bulkError }}</p>
                    </div>
                </div>

                <div v-if="bulkLoading && !bulkJob" class="state-card muted-card">
                    <span class="loader" aria-hidden="true"></span>
                    <strong>Memuat status bulk upload ZIP</strong>
                    <p>Mohon tunggu sebentar.</p>
                </div>

                <section v-if="bulkJob" class="panel-block">
                    <div class="section-heading">
                        <div>
                            <h2>Preview job terbaru #{{ bulkJob.bulk_upload_job_id }}</h2>
                            <p>{{ bulkJob.original_filename || 'ZIP bulk upload' }} · {{ bulkJob.created_at ? dateTime(bulkJob.created_at) : '-' }}</p>
                        </div>
                        <div class="page-actions">
                            <span :class="['status-pill', bulkJobTone(bulkJob.status)]">{{ bulkJobStatusLabel(bulkJob.status) }}</span>
                            <button type="button" class="secondary-btn" :disabled="bulkLoading" @click="loadBulkJob(bulkJob.bulk_upload_job_id)">{{ bulkLoading ? 'Memuat...' : 'Refresh status' }}</button>
                            <button type="button" :disabled="!canConfirmBulkJob" @click="confirmBulkJob(bulkJob)">{{ bulkConfirming ? 'Menyimpan...' : 'Konfirmasi simpan file' }}</button>
                        </div>
                    </div>

                    <div v-if="bulkJob.error_message" class="notice-box error">
                        <div>
                            <strong>Preview gagal</strong>
                            <p>{{ bulkJob.error_message }}</p>
                        </div>
                    </div>

                    <div class="metric-grid">
                        <article class="metric-card"><span>File cocok</span><strong>{{ matchedCount }}</strong></article>
                        <article class="metric-card"><span>Penerima belum punya file</span><strong>{{ summaryCount('missing_recipients') }}</strong></article>
                        <article class="metric-card"><span>Tidak cocok</span><strong>{{ summaryCount('unmatched_entries', 'unmatched') }}</strong></article>
                        <article class="metric-card"><span>Duplikat</span><strong>{{ summaryCount('duplicate_entries', 'duplicate') }}</strong></article>
                        <article class="metric-card"><span>Ambigu</span><strong>{{ summaryCount('ambiguous_entries', 'ambiguous') }}</strong></article>
                        <article class="metric-card"><span>File invalid</span><strong>{{ summaryCount('invalid_entries', 'invalid') }}</strong></article>
                        <article class="metric-card"><span>File existing akan diganti</span><strong>{{ summaryCount('will_replace_entries', 'will_replace') }}</strong></article>
                    </div>

                    <div v-if="hasSkippedBulkItems" class="notice-box info">
                        <div>
                            <strong>Perhatian sebelum konfirmasi</strong>
                            <p>{{ skippedBulkWarningText }} Hanya file dengan status File cocok yang akan disimpan.</p>
                        </div>
                    </div>

                    <div v-if="bulkJobEntries.length" class="table-wrap">
                        <table>
                            <thead><tr><th>File</th><th>Match</th><th>Penerima</th><th>Status</th><th>Catatan</th></tr></thead>
                            <tbody>
                                <tr v-for="entry in bulkJobEntries" :key="entry.bulk_upload_entry_id">
                                    <td><strong>{{ entry.original_filename || entry.display_filename || entry.entry_path }}</strong><small>{{ entry.entry_path }} · {{ formatBytes(entry.file_size_bytes) }}</small></td>
                                    <td><span :class="['status-pill', bulkEntryTone(entry.match_status)]">{{ bulkEntryStatusLabel(entry.match_status) }}</span></td>
                                    <td><strong>{{ entry.recipient?.identifier || entry.identifier || '-' }}</strong><small>{{ entry.recipient?.name_snapshot || '-' }}</small></td>
                                    <td>{{ entry.extension ? `.${entry.extension}` : '-' }}<small>{{ entry.mime_type || '-' }}</small></td>
                                    <td>{{ entry.match_reason || '-' }}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div v-else class="state-card muted-card">
                        <strong>Belum ada tabel hasil matching</strong>
                        <p>Hasil matching akan muncul setelah preview ZIP selesai diproses.</p>
                    </div>
                </section>
            </div>

            <AsyncState :loading="recipientLoading" :error="recipientError" :empty="recipients.length === 0" empty-title="Belum ada penerima" empty-text="Publish distribusi untuk membuat daftar penerima." @retry="loadRecipients">
                <div class="table-wrap">
                    <table>
                        <thead><tr><th>Penerima</th><th>Status</th><th>File</th><th>Upload</th></tr></thead>
                        <tbody>
                            <tr v-for="recipient in recipients" :key="recipient.recipient_id">
                                <td><strong>{{ recipient.identifier }}</strong><small>{{ recipient.name_snapshot || '-' }}</small></td>
                                <td><StatusPill :status="recipient.delivery_status" /></td>
                                <td>{{ recipient.file?.display_filename || '-' }}</td>
                                <td><label class="file-action">Pilih file<input type="file" @change="uploadRecipient($event, recipient)" /></label></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </AsyncState>
        </section>
    </section>
</template>

<script setup>
import { computed, onBeforeUnmount, onMounted, reactive, ref } from 'vue';
import AsyncState from '../../components/AsyncState.vue';
import PageHeader from '../../components/PageHeader.vue';
import StatusPill from '../../components/StatusPill.vue';
import TargetPicker from '../../components/TargetPicker.vue';
import { statusLabel } from '../../constants/navigation';
import { arsipApi } from '../../services/arsipApi';
import { confirmAction } from '../../services/dialogs';
import { toErrorMessage } from '../../services/http';
import { useAppStore } from '../../stores/appStore';
import { bytes as formatBytes, dateTime } from '../../utils/format';

const app = useAppStore();
const loading = ref(false);
const previewLoading = ref(false);
const recipientLoading = ref(false);
const bulkLoading = ref(false);
const bulkUploading = ref(false);
const bulkConfirming = ref(false);
const error = ref('');
const previewError = ref('');
const recipientError = ref('');
const bulkError = ref('');
const distributions = ref([]);
const recipients = ref([]);
const bulkJobs = ref([]);
const bulkJob = ref(null);
const bulkZipFile = ref(null);
const bulkFileInput = ref(null);
const preview = ref(null);
const selectedId = ref('');
const selectedDistribution = ref(null);
const targeting = ref(null);
const form = reactive({ title: '', description: '' });
let bulkPollingTimer = null;

const bulkUploadTerminalStatuses = ['preview_ready', 'failed', 'expired', 'cancelled'];
const bulkTerminalStatuses = [...bulkUploadTerminalStatuses, 'confirmed'];

const isSelectedDistributionPublished = computed(() => selectedDistribution.value?.status === 'published');
const bulkJobEntries = computed(() => bulkJob.value?.entries || []);
const matchedCount = computed(() => summaryCount('matched_entries', 'matched'));
const skippedEntriesCount = computed(() => (
    summaryCount('skipped')
    || summaryCount('unmatched_entries', 'unmatched')
        + summaryCount('duplicate_entries', 'duplicate')
        + summaryCount('ambiguous_entries', 'ambiguous')
        + summaryCount('invalid_entries', 'invalid')
));
const hasSkippedBulkItems = computed(() => skippedEntriesCount.value > 0 || summaryCount('missing_recipients') > 0 || summaryCount('will_replace_entries', 'will_replace') > 0);
const canConfirmBulkJob = computed(() => bulkJob.value?.status === 'preview_ready' && matchedCount.value > 0 && !bulkConfirming.value);
const skippedBulkWarningText = computed(() => bulkSkipText());

function payload() {
    return {
        ...form,
        ...targeting.value.payload,
    };
}

async function load() {
    loading.value = true;
    error.value = '';
    try {
        const data = await arsipApi.distributions();
        distributions.value = data.distributions || [];
        if (selectedId.value) {
            selectedDistribution.value = distributions.value.find((item) => item.distribution_id === selectedId.value) || selectedDistribution.value;
            if (!isSelectedDistributionPublished.value) clearBulkState();
        }
    } catch (err) { error.value = toErrorMessage(err); } finally { loading.value = false; }
}

async function saveDistribution() {
    if (!targeting.value?.canSubmit) {
        app.notify('error', 'Pilih target penerima terlebih dahulu.');
        return;
    }

    const confirmed = await confirmAction({
        title: 'Simpan draft distribusi?',
        text: `Target: ${targeting.value.summary}. Draft bisa dipublish setelah dicek.`,
        confirmText: 'Simpan draft',
    });
    if (!confirmed) return;

    await arsipApi.createDistribution(payload());
    app.notify('success', 'Distribusi berhasil dibuat.');
    form.title = '';
    form.description = '';
    preview.value = null;
    await load();
}

async function previewTargets() {
    if (!targeting.value?.canSubmit) {
        previewError.value = 'Pilih target penerima terlebih dahulu.';
        return;
    }

    previewLoading.value = true;
    previewError.value = '';
    try { preview.value = (await arsipApi.previewDistributionTargets(payload())).preview; }
    catch (err) { previewError.value = toErrorMessage(err); }
    finally { previewLoading.value = false; }
}

async function publish(item) {
    const confirmed = await confirmAction({
        title: 'Publish distribusi?',
        text: 'Daftar penerima akan dibuat dan file bisa mulai diupload per penerima.',
        confirmText: 'Publish',
        icon: 'warning',
    });
    if (!confirmed) return;

    await arsipApi.publishDistribution(item.distribution_id);
    app.notify('success', 'Distribusi berhasil dipublish.');
    await load();
}

async function selectDistribution(item) {
    selectedId.value = item.distribution_id;
    selectedDistribution.value = item;
    await Promise.all([loadRecipients(), loadBulkJobs()]);
}

async function refreshSelectedDistribution() {
    await Promise.all([loadRecipients(), loadBulkJobs()]);
}

async function loadRecipients() {
    if (!selectedId.value) return;
    recipientLoading.value = true;
    recipientError.value = '';
    try { recipients.value = (await arsipApi.distributionRecipients(selectedId.value)).recipients || []; }
    catch (err) { recipientError.value = toErrorMessage(err); }
    finally { recipientLoading.value = false; }
}

async function uploadRecipient(event, recipient) {
    const file = event.target.files?.[0];
    event.target.value = '';
    if (!file) return;

    const confirmed = await confirmAction({
        title: 'Upload file penerima?',
        text: `${recipient.identifier} - ${recipient.name_snapshot || 'tanpa nama'}`,
        confirmText: 'Upload',
    });
    if (!confirmed) return;

    const formData = new FormData();
    formData.append('file', file);
    await arsipApi.uploadRecipientFile(recipient.recipient_id, formData);
    app.notify('success', 'File penerima berhasil diupload.');
    await loadRecipients();
}

function selectBulkZip(event) {
    bulkZipFile.value = event.target.files?.[0] || null;
}

async function loadBulkJobs() {
    stopBulkPolling();
    if (!selectedId.value || !isSelectedDistributionPublished.value) {
        clearBulkState();
        return;
    }

    bulkLoading.value = true;
    bulkError.value = '';
    try {
        const data = await arsipApi.distributionBulkUploadJobs(selectedId.value);
        bulkJobs.value = data.bulk_upload_jobs || [];
        const latestJob = bulkJobs.value[0] || null;
        bulkJob.value = latestJob;
        if (latestJob?.bulk_upload_job_id) {
            await loadBulkJob(latestJob.bulk_upload_job_id, { silent: true });
            if (bulkJob.value?.bulk_upload_job_id && !bulkTerminalStatuses.includes(bulkJob.value.status)) {
                startBulkPolling(bulkJob.value.bulk_upload_job_id);
            }
        }
    } catch (err) {
        bulkError.value = toErrorMessage(err);
    } finally {
        bulkLoading.value = false;
    }
}

async function uploadBulkZip() {
    if (!selectedId.value || !isSelectedDistributionPublished.value) {
        bulkError.value = 'Bulk upload ZIP hanya tersedia untuk distribusi yang sudah dipublish.';
        return;
    }
    if (!bulkZipFile.value) {
        bulkError.value = 'Pilih file ZIP terlebih dahulu.';
        return;
    }

    stopBulkPolling();
    bulkUploading.value = true;
    bulkError.value = '';
    try {
        const formData = new FormData();
        formData.append('zip_file', bulkZipFile.value);
        const data = await arsipApi.createDistributionBulkUploadJob(selectedId.value, formData);
        bulkJob.value = data.bulk_upload_job;
        mergeBulkJob(data.bulk_upload_job);
        bulkZipFile.value = null;
        if (bulkFileInput.value) bulkFileInput.value.value = '';
        app.notify('success', 'Bulk upload ZIP dibuat. Menunggu preview matching.');
        startBulkPolling(data.bulk_upload_job.bulk_upload_job_id);
    } catch (err) {
        bulkError.value = toErrorMessage(err);
        app.notify('error', bulkError.value);
    } finally {
        bulkUploading.value = false;
    }
}

async function loadBulkJob(jobId, options = {}) {
    if (!jobId) return;
    if (!options.silent) {
        bulkLoading.value = true;
        bulkError.value = '';
    }

    try {
        const data = await arsipApi.distributionBulkUploadJob(jobId);
        bulkJob.value = data.bulk_upload_job;
        mergeBulkJob(data.bulk_upload_job);
        if (bulkTerminalStatuses.includes(data.bulk_upload_job?.status)) stopBulkPolling();
    } catch (err) {
        bulkError.value = toErrorMessage(err);
        stopBulkPolling();
    } finally {
        if (!options.silent) bulkLoading.value = false;
    }
}

async function confirmBulkJob(job) {
    if (!job || !canConfirmBulkJob.value) return;

    const confirmed = await confirmAction({
        title: `Simpan ${matchedCount.value} file yang cocok?`,
        text: `${bulkSkipText()} File cocok akan disimpan ke penerima dan file existing akan diganti jika ada.`,
        confirmText: 'Konfirmasi simpan file',
        icon: hasSkippedBulkItems.value ? 'warning' : 'question',
    });
    if (!confirmed) return;

    bulkConfirming.value = true;
    bulkError.value = '';
    stopBulkPolling();
    try {
        const data = await arsipApi.confirmDistributionBulkUploadJob(job.bulk_upload_job_id);
        bulkJob.value = data.bulk_upload_job;
        mergeBulkJob(data.bulk_upload_job);
        app.notify('success', 'File cocok berhasil disimpan ke penerima.');
        await loadRecipients();
    } catch (err) {
        bulkError.value = toErrorMessage(err);
        app.notify('error', bulkError.value);
    } finally {
        bulkConfirming.value = false;
    }
}

async function cancelBulkJob(job) {
    if (!job) return;

    const confirmed = await confirmAction({
        title: 'Batalkan bulk upload ZIP?',
        text: 'Preview ZIP yang dibatalkan tidak dapat dikonfirmasi.',
        confirmText: 'Batalkan preview',
        icon: 'warning',
    });
    if (!confirmed) return;

    bulkLoading.value = true;
    bulkError.value = '';
    try {
        const data = await arsipApi.cancelDistributionBulkUploadJob(job.bulk_upload_job_id);
        bulkJob.value = data.bulk_upload_job;
        mergeBulkJob(data.bulk_upload_job);
        stopBulkPolling();
        app.notify('success', 'Bulk upload ZIP dibatalkan.');
    } catch (err) {
        bulkError.value = toErrorMessage(err);
        app.notify('error', bulkError.value);
    } finally {
        bulkLoading.value = false;
    }
}

function startBulkPolling(jobId) {
    stopBulkPolling();
    if (!jobId) return;

    bulkPollingTimer = window.setTimeout(async () => {
        await loadBulkJob(jobId, { silent: true });
        if (bulkJob.value?.bulk_upload_job_id === jobId && !bulkTerminalStatuses.includes(bulkJob.value.status)) {
            startBulkPolling(jobId);
        }
    }, 4000);
}

function stopBulkPolling() {
    if (bulkPollingTimer) {
        window.clearTimeout(bulkPollingTimer);
        bulkPollingTimer = null;
    }
}

function clearBulkState() {
    stopBulkPolling();
    bulkJobs.value = [];
    bulkJob.value = null;
    bulkZipFile.value = null;
    bulkError.value = '';
    if (bulkFileInput.value) bulkFileInput.value.value = '';
}

function mergeBulkJob(job) {
    if (!job?.bulk_upload_job_id) return;
    const index = bulkJobs.value.findIndex((item) => item.bulk_upload_job_id === job.bulk_upload_job_id);
    if (index === -1) {
        bulkJobs.value = [job, ...bulkJobs.value];
        return;
    }

    bulkJobs.value = bulkJobs.value.map((item, itemIndex) => (itemIndex === index ? job : item));
}

function summaryCount(...keys) {
    const summary = bulkJob.value?.summary || {};
    for (const key of keys) {
        const value = Number(summary[key] ?? 0);
        if (value > 0) return value;
    }
    return 0;
}

function bulkSkipText() {
    const skippedParts = [];
    const notes = [];
    const missing = summaryCount('missing_recipients');
    const unmatched = summaryCount('unmatched_entries', 'unmatched');
    const duplicate = summaryCount('duplicate_entries', 'duplicate');
    const ambiguous = summaryCount('ambiguous_entries', 'ambiguous');
    const invalid = summaryCount('invalid_entries', 'invalid');
    const willReplace = summaryCount('will_replace_entries', 'will_replace');
    const skipped = summaryCount('skipped');

    if (missing) skippedParts.push(`${missing} penerima belum punya file`);
    if (unmatched) skippedParts.push(`${unmatched} file tidak cocok`);
    if (duplicate) skippedParts.push(`${duplicate} duplikat`);
    if (ambiguous) skippedParts.push(`${ambiguous} ambigu`);
    if (invalid) skippedParts.push(`${invalid} file invalid`);
    if (!skippedParts.length && skipped) skippedParts.push(`${skipped} file`);
    if (skippedParts.length) notes.push(`${skippedParts.join(', ')} akan dilewati.`);
    if (willReplace) notes.push(`File existing akan diganti untuk ${willReplace} penerima.`);

    return notes.length ? notes.join(' ') : 'Tidak ada file yang dilewati.';
}

function bulkJobStatusLabel(status) {
    return {
        uploaded: 'ZIP diterima',
        processing: 'Memproses preview',
        preview_ready: 'Preview siap',
        confirming: 'Menyimpan file',
        confirmed: 'Selesai disimpan',
        failed: 'Gagal',
        expired: 'Kedaluwarsa',
        cancelled: 'Dibatalkan',
    }[status] || statusLabel(status);
}

function bulkJobTone(status) {
    if (['preview_ready', 'confirmed'].includes(status)) return 'ok';
    if (['failed', 'expired', 'cancelled'].includes(status)) return 'danger';
    if (['uploaded', 'processing', 'confirming'].includes(status)) return 'warn';
    return 'neutral';
}

function bulkEntryStatusLabel(status) {
    return {
        matched: 'File cocok',
        unmatched: 'Tidak cocok',
        duplicate: 'Duplikat',
        ambiguous: 'Ambigu',
        invalid: 'File invalid',
        confirmed: 'Tersimpan',
        skipped: 'Dilewati',
        failed: 'Gagal',
    }[status] || statusLabel(status);
}

function bulkEntryTone(status) {
    if (['matched', 'confirmed'].includes(status)) return 'ok';
    if (['duplicate', 'ambiguous'].includes(status)) return 'warn';
    if (['invalid', 'failed'].includes(status)) return 'danger';
    return 'neutral';
}

onMounted(load);
onBeforeUnmount(stopBulkPolling);
</script>

// resources/js/features/arsip-digital/admin/AdminDistributions.jsx
import { useEffect, useState } from 'react';
import Swal from 'sweetalert2';
import { arsipApi } from '../../../libs/arsip_api';
import { formatArsipError } from '../../../libs/arsip_http';
import { bytes, dateTime } from '../../../libs/format';
import { customSwal } from '../../../components/CustomSwal';
import PageHeader from '../../../components/PageHeader';
import StatusChip from '../../../components/StatusChip';
import CustomDataTable from '../../../components/CustomDataTable';
import TargetPicker from '../components/TargetPicker';
import { BULK_ZIP_TERMINAL, usePollingJob } from '../hooks/usePollingJob';
import { Alert, Button, Dialog, DialogActions, DialogContent, DialogTitle, MenuItem, TextField } from '@mui/material';
import AddOutlined from '@mui/icons-material/AddOutlined';
import CloudUploadOutlined from '@mui/icons-material/CloudUploadOutlined';
import DownloadOutlined from '@mui/icons-material/DownloadOutlined';
import RefreshOutlined from '@mui/icons-material/RefreshOutlined';
import SearchOutlined from '@mui/icons-material/SearchOutlined';

const buttonSx = { borderRadius: '0.5rem', textTransform: 'none', fontFamily: 'Plus Jakarta Sans, sans-serif' };
const emptyForm = { title: '', description: '' };

function unwrapList(response, keys) {
    const payload = response?.data ?? response ?? {};
    const list = Array.isArray(payload) ? payload : keys.map((key) => payload[key]).find(Array.isArray) ?? payload.data ?? [];
    return { data: Array.isArray(list) ? list : [], meta: payload.meta ?? payload.pagination ?? response?.meta ?? null };
}

function unwrapOne(response, keys) {
    const payload = response?.data ?? response ?? {};
    for (const key of keys) if (payload[key]) return payload[key];
    return payload;
}

function distributionId(row) {
    return row.distribution_id ?? row.id;
}

function recipientId(row) {
    return row.recipient_id ?? row.distribution_recipient_id ?? row.id;
}

function jobId(row) {
    return row.bulk_upload_job_id ?? row.id;
}

function fileOf(row) {
    return row.file ?? row.distribution_file ?? row.current_file ?? null;
}

function distributionFileId(file) {
    return file?.file_id ?? file?.id ?? file?.distribution_file_id;
}

function canSubmitTarget(payload) {
    if (!payload?.target_role || !payload?.scope_type) return false;
    if (payload.scope_type === 'specific') return (payload.target_identifiers || []).length > 0;
    return true;
}

async function confirmAction(title, text, confirmButtonText = 'Ya') {
    const result = await Swal.fire({ title, text, icon: 'question', showCancelButton: true, confirmButtonText, cancelButtonText: 'Batal' });
    return result.isConfirmed;
}

function normalizeTarget(row) {
    if (!row) return null;
    return { target_role: row.target_role || 'mahasiswa', scope_type: row.scope_type || 'filter', target_filters: row.target_filters || {}, target_identifiers: row.target_identifiers || [] };
}

function entryStatus(entry) {
    return entry.match_status ?? entry.status ?? '-';
}

function summaryCount(job, ...keys) {
    const summary = job?.summary || job?.preview_summary || {};
    for (const key of keys) {
        const value = Number(summary[key] ?? job?.[key] ?? 0);
        if (value > 0) return value;
    }
    return 0;
}

export default function AdminDistributions() {
    const [rows, setRows] = useState([]);
    const [meta, setMeta] = useState(null);
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState('');
    const [filters, setFilters] = useState({ search: '', status: '', target_role: '' });
    const [dialogOpen, setDialogOpen] = useState(false);
    const [editing, setEditing] = useState(null);
    const [form, setForm] = useState(emptyForm);
    const [targetPayload, setTargetPayload] = useState(null);
    const [preview, setPreview] = useState(null);
    const [previewLoading, setPreviewLoading] = useState(false);
    const [saving, setSaving] = useState(false);
    const [selected, setSelected] = useState(null);
    const [recipients, setRecipients] = useState([]);
    const [recipientsMeta, setRecipientsMeta] = useState(null);
    const [recipientsLoading, setRecipientsLoading] = useState(false);
    const [jobs, setJobs] = useState([]);
    const [jobsLoading, setJobsLoading] = useState(false);
    const [bulkFile, setBulkFile] = useState(null);
    const [bulkJob, setBulkJob] = useState(null);
    const [bulkError, setBulkError] = useState('');
    const [bulkUploading, setBulkUploading] = useState(false);
    const [actionLoading, setActionLoading] = useState(false);
    const selectedId = selected ? distributionId(selected) : null;
    const activeJobId = bulkJob ? jobId(bulkJob) : null;

    const loadDistributions = async () => {
        setLoading(true);
        setError('');
        try {
            const response = await arsipApi.distributions({ ...filters, per_page: 50 });
            const unwrapped = unwrapList(response, ['distributions']);
            setRows(unwrapped.data);
            setMeta(unwrapped.meta);
            if (selectedId) setSelected(unwrapped.data.find((item) => distributionId(item) === selectedId) || selected);
        } catch (err) {
            const formatted = await formatArsipError(err);
            setError(formatted.message);
            customSwal.toast.error({ message: formatted.message });
        } finally {
            setLoading(false);
        }
    };

    const loadRecipients = async (distribution = selected) => {
        if (!distribution) return;
        setRecipientsLoading(true);
        try {
            const response = await arsipApi.distributionRecipients(distributionId(distribution), { per_page: 50 });
            const unwrapped = unwrapList(response, ['recipients']);
            setRecipients(unwrapped.data);
            setRecipientsMeta(unwrapped.meta);
        } catch (err) {
            const formatted = await formatArsipError(err);
            customSwal.toast.error({ message: formatted.message });
        } finally {
            setRecipientsLoading(false);
        }
    };

    const loadJobs = async (distribution = selected) => {
        if (!distribution) return;
        setJobsLoading(true);
        setBulkError('');
        try {
            const response = await arsipApi.distributionBulkUploadJobs(distributionId(distribution), { per_page: 10 });
            const unwrapped = unwrapList(response, ['bulk_upload_jobs', 'jobs']);
            setJobs(unwrapped.data);
            const latest = unwrapped.data[0] || null;
            setBulkJob(latest);
        } catch (err) {
            const formatted = await formatArsipError(err);
            setBulkError(formatted.message);
        } finally {
            setJobsLoading(false);
        }
    };

    usePollingJob({
        enabled: Boolean(activeJobId && !BULK_ZIP_TERMINAL.includes(bulkJob?.status)),
        jobId: activeJobId,
        pollFn: arsipApi.distributionBulkUploadJob,
        intervalMs: 4000,
        terminalStatuses: BULK_ZIP_TERMINAL,
        maxDurationMs: 180000,
        onUpdate: (response) => setBulkJob(unwrapOne(response, ['bulk_upload_job', 'job'])),
        onTimeoutWarning: () => {
            setBulkError('Preview ZIP masih diproses lebih lama dari biasanya. Polling tetap berjalan sampai status final.');
        },
        onTerminal: ({ data }) => {
            if (data) setBulkJob(data);
        },
    });

    useEffect(() => {
        loadDistributions();
    }, []);

    const openCreate = () => {
        setEditing(null);
        setForm(emptyForm);
        setTargetPayload(null);
        setPreview(null);
        setDialogOpen(true);
    };

    const openEdit = (row) => {
        setEditing(row);
        setForm({ title: row.title || '', description: row.description || '' });
        setTargetPayload(normalizeTarget(row));
        setPreview(null);
        setDialogOpen(true);
    };

    const buildPayload = () => ({ title: form.title, description: form.description || null, ...targetPayload });

    const previewTargets = async () => {
        if (!canSubmitTarget(targetPayload)) {
            customSwal.toast.error({ message: 'Pilih target penerima terlebih dahulu.' });
            return;
        }
        setPreviewLoading(true);
        try {
            const response = await arsipApi.previewDistributionTargets(buildPayload());
            setPreview(unwrapOne(response, ['preview']));
        } catch (err) {
            const formatted = await formatArsipError(err);
            customSwal.toast.error({ message: formatted.message });
        } finally {
            setPreviewLoading(false);
        }
    };

    const saveDistribution = async () => {
        if (!form.title.trim()) {
            customSwal.toast.error({ message: 'Judul wajib diisi.' });
            return;
        }
        if (!canSubmitTarget(targetPayload)) {
            customSwal.toast.error({ message: 'Pilih target penerima terlebih dahulu.' });
            return;
        }
        setSaving(true);
        try {
            if (editing) {
                await arsipApi.updateDistribution(distributionId(editing), buildPayload());
                customSwal.toast.success({ message: 'Draft distribusi diperbarui.' });
            } else {
                await arsipApi.createDistribution(buildPayload());
                customSwal.toast.success({ message: 'Draft distribusi dibuat.' });
            }
            setDialogOpen(false);
            await loadDistributions();
        } catch (err) {
            const formatted = await formatArsipError(err);
            customSwal.toast.error({ message: formatted.message });
        } finally {
            setSaving(false);
        }
    };

    const publish = async (row) => {
        if (!(await confirmAction('Publish distribusi?', 'Daftar penerima akan dibuat dan file bisa diupload.', 'Publish'))) return;
        try {
            await arsipApi.publishDistribution(distributionId(row));
            customSwal.toast.success({ message: 'Distribusi dipublish.' });
            await loadDistributions();
        } catch (err) {
            const formatted = await formatArsipError(err);
            customSwal.toast.error({ message: formatted.message });
        }
    };

    const remove = async (row) => {
        if (!(await confirmAction('Hapus distribusi?', 'Distribusi akan dihapus permanen.', 'Hapus'))) return;
        try {
            await arsipApi.deleteDistribution(distributionId(row));
            customSwal.toast.success({ message: 'Distribusi dihapus.' });
            if (distributionId(row) === selectedId) setSelected(null);
            await loadDistributions();
        } catch (err) {
            const formatted = await formatArsipError(err);
            customSwal.toast.error({ message: formatted.message });
        }
    };

    const selectDistribution = async (row) => {
        setSelected(row);
        setRecipients([]);
        setJobs([]);
        setBulkJob(null);
        setBulkFile(null);
        await Promise.all([loadRecipients(row), loadJobs(row)]);
    };

    const uploadRecipient = async (recipient, file) => {
        if (!file) return;
        setActionLoading(true);
        try {
            const formData = new FormData();
            formData.append('file', file);
            await arsipApi.uploadRecipientFile(recipientId(recipient), formData);
            customSwal.toast.success({ message: 'File penerima berhasil diupload.' });
            await loadRecipients();
        } catch (err) {
            const formatted = await formatArsipError(err);
            customSwal.toast.error({ message: formatted.message });
        } finally {
            setActionLoading(false);
        }
    };

    const downloadRecipientFile = async (recipient) => {
        const file = fileOf(recipient);
        if (!distributionFileId(file)) return;
        try {
            await arsipApi.downloadDistributionFile(file);
        } catch (err) {
            const formatted = await formatArsipError(err);
            customSwal.toast.error({ message: formatted.message });
        }
    };

    const uploadBulkZip = async () => {
        if (!selectedId || !bulkFile) return;
        setBulkUploading(true);
        setBulkError('');
        try {
            const formData = new FormData();
            formData.append('zip_file', bulkFile);
            const response = await arsipApi.createDistributionBulkUploadJob(selectedId, formData);
            const job = unwrapOne(response, ['bulk_upload_job', 'job']);
            setBulkJob(job);
            setBulkFile(null);
            customSwal.toast.success({ message: 'Bulk ZIP dibuat. Menunggu preview matching.' });
            await loadJobs();
        } catch (err) {
            const formatted = await formatArsipError(err);
            setBulkError(formatted.message);
            customSwal.toast.error({ message: formatted.message });
        } finally {
            setBulkUploading(false);
        }
    };

    const confirmBulk = async () => {
        if (!bulkJob || bulkJob.status !== 'preview_ready' || bulkJob.confirmable === false) return;
        if (!(await confirmAction('Konfirmasi simpan file cocok?', 'Unmatched, duplicate, dan invalid tidak ikut disimpan.', 'Konfirmasi'))) return;
        setActionLoading(true);
        try {
            const response = await arsipApi.confirmDistributionBulkUploadJob(activeJobId);
            setBulkJob(unwrapOne(response, ['bulk_upload_job', 'job']));
            setBulkFile(null);
            customSwal.toast.success({ message: 'Bulk ZIP dikonfirmasi.' });
            await Promise.all([loadRecipients(), loadJobs()]);
        } catch (err) {
            const formatted = await formatArsipError(err);
            setBulkError(formatted.message);
            customSwal.toast.error({ message: formatted.message });
        } finally {
            setActionLoading(false);
        }
    };

    const cancelBulk = async () => {
        if (!bulkJob || !(await confirmAction('Batalkan bulk ZIP?', 'Preview tidak dapat dikonfirmasi setelah dibatalkan.', 'Batalkan'))) return;
        setActionLoading(true);
        try {
            const response = await arsipApi.cancelDistributionBulkUploadJob(activeJobId);
            setBulkJob(unwrapOne(response, ['bulk_upload_job', 'job']));
            setBulkFile(null);
            customSwal.toast.success({ message: 'Bulk ZIP dibatalkan.' });
            await loadJobs();
        } catch (err) {
            const formatted = await formatArsipError(err);
            setBulkError(formatted.message);
            customSwal.toast.error({ message: formatted.message });
        } finally {
            setActionLoading(false);
        }
    };

    const refreshBulkJob = async () => {
        if (!activeJobId) return;
        try {
            const response = await arsipApi.distributionBulkUploadJob(activeJobId);
            setBulkJob(unwrapOne(response, ['bulk_upload_job', 'job']));
            setBulkError('');
        } catch (err) {
            const formatted = await formatArsipError(err);
            setBulkError(formatted.message);
            customSwal.toast.error({ message: formatted.message });
        }
    };

    const columns = [
        { field: 'title', headerName: 'Judul', flex: 1, minWidth: 220, renderCell: (params) => <button type="button" className="text-blue-600 font-semibold hover:underline text-left" onClick={() => selectDistribution(params.row)}>{params.row.title || '-'}</button> },
        { field: 'status', headerName: 'Status', width: 130, renderCell: (params) => <StatusChip status={params.row.status} /> },
        { field: 'target_role', headerName: 'Target', width: 150, renderCell: (params) => `${params.row.target_role || '-'} · ${params.row.scope_type || '-'}` },
        { field: 'recipients_count', headerName: 'Penerima', width: 120, valueGetter: (value, row) => row.recipients_count ?? row.total_recipients ?? '-' },
        { field: 'published_at', headerName: 'Published', width: 170, renderCell: (params) => dateTime(params.row.published_at) },
        { field: 'actions', headerName: 'Aksi', width: 330, sortable: false, renderCell: (params) => <div className="flex gap-1 flex-wrap"><Button size="small" onClick={() => selectDistribution(params.row)} sx={buttonSx}>Detail</Button>{params.row.status === 'draft' && <Button size="small" onClick={() => openEdit(params.row)} sx={buttonSx}>Edit</Button>}{params.row.status === 'draft' && <Button size="small" onClick={() => publish(params.row)} sx={buttonSx}>Publish</Button>}<Button size="small" color="error" onClick={() => remove(params.row)} sx={buttonSx}>Hapus</Button></div> },
    ];

    const recipientColumns = [
        { field: 'identifier', headerName: 'Identifier', width: 150, valueGetter: (value, row) => row.identifier || '-' },
        { field: 'name_snapshot', headerName: 'Nama', flex: 1, minWidth: 190, valueGetter: (value, row) => row.name_snapshot || row.name || '-' },
        { field: 'delivery_status', headerName: 'Status', width: 140, renderCell: (params) => <StatusChip status={params.row.delivery_status || params.row.status || 'pending'} /> },
        { field: 'file', headerName: 'File', width: 220, renderCell: (params) => fileOf(params.row)?.display_filename || fileOf(params.row)?.original_filename || '-' },
        { field: 'uploaded_at', headerName: 'Uploaded', width: 170, renderCell: (params) => dateTime(params.row.uploaded_at || fileOf(params.row)?.created_at) },
        { field: 'actions', headerName: 'Aksi', width: 260, sortable: false, renderCell: (params) => <div className="flex gap-1 flex-wrap"><Button component="label" size="small" variant="outlined" disabled={actionLoading} sx={{ ...buttonSx, borderColor: '#e4e4e7', color: '#3f3f46' }}>Upload<input type="file" hidden onChange={(event) => uploadRecipient(params.row, event.target.files?.[0] || null)} /></Button><Button size="small" disabled={!distributionFileId(fileOf(params.row))} onClick={() => downloadRecipientFile(params.row)} sx={buttonSx}><DownloadOutlined sx={{ fontSize: 16 }} /></Button></div> },
    ];

    const jobColumns = [
        { field: 'bulk_upload_job_id', headerName: 'Job', width: 100, valueGetter: (value, row) => jobId(row) },
        { field: 'status', headerName: 'Status', width: 140, renderCell: (params) => <StatusChip status={params.row.status} /> },
        { field: 'original_filename', headerName: 'ZIP', flex: 1, minWidth: 180, valueGetter: (value, row) => row.original_filename || row.filename || '-' },
        { field: 'created_at', headerName: 'Dibuat', width: 170, renderCell: (params) => dateTime(params.row.created_at) },
        { field: 'actions', headerName: 'Aksi', width: 110, renderCell: (params) => <Button size="small" onClick={() => setBulkJob(params.row)} sx={buttonSx}>Lihat</Button> },
    ];

    const entryRows = bulkJob?.entries || bulkJob?.preview_entries || [];
    const canConfirm = bulkJob?.status === 'preview_ready' && bulkJob?.confirmable !== false;

    return (
        <div className="font-jakarta">
            <PageHeader title="Distribusi Berkas" subtitle="Kelola distribusi, penerima, upload file, dan bulk ZIP." actions={<><Button variant="outlined" startIcon={<RefreshOutlined />} onClick={loadDistributions} sx={{ ...buttonSx, borderColor: '#e4e4e7', color: '#3f3f46' }}>Refresh</Button><Button variant="contained" startIcon={<AddOutlined />} onClick={openCreate} sx={{ ...buttonSx, backgroundColor: '#2563eb' }}>Buat Distribusi</Button></>} />
            {error && <Alert severity="error" sx={{ mb: 2, borderRadius: '0.5rem' }}>{error}</Alert>}
            <section className="bg-white rounded-lg border border-zinc-200 p-4 mb-4 flex flex-wrap gap-3"><TextField size="small" label="Cari" value={filters.search} onChange={(event) => setFilters((prev) => ({ ...prev, search: event.target.value }))} sx={{ minWidth: 220 }} /><TextField size="small" select label="Status" value={filters.status} onChange={(event) => setFilters((prev) => ({ ...prev, status: event.target.value }))} sx={{ minWidth: 150 }}><MenuItem value="">Semua</MenuItem><MenuItem value="draft">Draft</MenuItem><MenuItem value="published">Published</MenuItem><MenuItem value="archived">Archived</MenuItem></TextField><TextField size="small" select label="Target" value={filters.target_role} onChange={(event) => setFilters((prev) => ({ ...prev, target_role: event.target.value }))} sx={{ minWidth: 150 }}><MenuItem value="">Semua</MenuItem><MenuItem value="mahasiswa">Mahasiswa</MenuItem><MenuItem value="dosen">Dosen</MenuItem></TextField><Button variant="contained" startIcon={<SearchOutlined />} onClick={loadDistributions} sx={{ ...buttonSx, backgroundColor: '#2563eb' }}>Terapkan Filter</Button></section>
            {!meta && rows.length > 0 && <Alert severity="info" sx={{ mb: 2, borderRadius: '0.5rem' }}>Backend pagination distribusi belum tersedia. Data dipaginasi di browser.</Alert>}
            <section className="bg-white rounded-lg border border-zinc-200 mb-4"><CustomDataTable rows={rows} columns={columns} loading={loading} getRowId={(row) => distributionId(row)} pageSize={25} pageSizeOptions={[25, 50]} /></section>
            {selected && <section className="bg-white rounded-lg border border-zinc-200 p-4 mb-4"><div className="flex items-center justify-between gap-3 flex-wrap mb-3"><div><h2 className="text-sm font-semibold text-zinc-800">Penerima Distribusi</h2><p className="text-xs text-zinc-500">{selected.title} · {selected.status}</p></div><Button variant="outlined" onClick={() => Promise.all([loadRecipients(), loadJobs()])} sx={{ ...buttonSx, borderColor: '#e4e4e7', color: '#3f3f46' }}>Refresh Detail</Button></div>{!recipientsMeta && recipients.length > 0 && <Alert severity="info" sx={{ mb: 2, borderRadius: '0.5rem' }}>Backend pagination penerima belum tersedia. Data dipaginasi di browser.</Alert>}<CustomDataTable rows={recipients} columns={recipientColumns} loading={recipientsLoading} getRowId={(row) => recipientId(row)} pageSize={25} pageSizeOptions={[25, 50]} /></section>}
            {selected && <section className="bg-white rounded-lg border border-zinc-200 p-4"><div className="mb-3"><h2 className="text-sm font-semibold text-zinc-800">Bulk Upload ZIP</h2><p className="text-xs text-zinc-500 mt-1">Upload ZIP berisi file personal. Backend mencocokkan nama file ke identifier penerima dan menampilkan preview. File unmatched, duplicate, dan invalid tidak ikut disimpan saat konfirmasi.</p></div>{bulkError && <Alert severity="warning" sx={{ mb: 2, borderRadius: '0.5rem' }}>{bulkError}</Alert>}<div className="flex flex-wrap gap-2 mb-3"><Button component="label" variant="outlined" startIcon={<CloudUploadOutlined />} sx={{ ...buttonSx, borderColor: '#e4e4e7', color: '#3f3f46' }}>{bulkFile ? `${bulkFile.name} · ${bytes(bulkFile.size)}` : 'Pilih ZIP'}<input type="file" hidden accept=".zip,application/zip,application/x-zip-compressed" onChange={(event) => setBulkFile(event.target.files?.[0] || null)} /></Button><Button variant="contained" disabled={bulkUploading || !bulkFile} onClick={uploadBulkZip} sx={{ ...buttonSx, backgroundColor: '#2563eb' }}>{bulkUploading ? 'Mengunggah...' : 'Upload ZIP & Preview'}</Button><Button variant="outlined" disabled={!bulkJob} onClick={refreshBulkJob} sx={{ ...buttonSx, borderColor: '#e4e4e7', color: '#3f3f46' }}>Refresh Job</Button><Button variant="contained" disabled={!canConfirm || actionLoading} onClick={confirmBulk} sx={{ ...buttonSx, backgroundColor: '#2563eb' }}>Konfirmasi</Button><Button color="error" disabled={!bulkJob || BULK_ZIP_TERMINAL.includes(bulkJob.status) || actionLoading} onClick={cancelBulk} sx={buttonSx}>Batalkan</Button></div><div className="grid grid-cols-2 md:grid-cols-5 gap-3 mb-3">{[['Matched', summaryCount(bulkJob, 'matched_entries', 'matched')], ['Unmatched', summaryCount(bulkJob, 'unmatched_entries', 'unmatched')], ['Duplicate', summaryCount(bulkJob, 'duplicate_entries', 'duplicate')], ['Invalid', summaryCount(bulkJob, 'invalid_entries', 'invalid')], ['Replace', summaryCount(bulkJob, 'will_replace_entries', 'will_replace')]].map(([label, value]) => <div key={label} className="rounded-lg bg-zinc-50 border border-zinc-200 p-3"><span className="text-xs text-zinc-500">{label}</span><strong className="block text-lg text-zinc-800">{value}</strong></div>)}</div>{bulkJob && <Alert severity={bulkJob.status === 'preview_ready' ? 'success' : 'info'} sx={{ mb: 2, borderRadius: '0.5rem' }}>Job #{activeJobId} · {bulkJob.status}. Konfirmasi aktif hanya saat preview_ready dan backend mengizinkan.</Alert>}<CustomDataTable rows={entryRows} columns={[{ field: 'original_filename', headerName: 'File', flex: 1, minWidth: 220, valueGetter: (value, row) => row.original_filename || row.display_filename || row.entry_path || '-' }, { field: 'identifier', headerName: 'Identifier', width: 150, valueGetter: (value, row) => row.identifier || row.parsed_identifier || '-' }, { field: 'recipient', headerName: 'Penerima', width: 200, renderCell: (params) => params.row.recipient?.identifier || params.row.recipient?.name_snapshot || '-' }, { field: 'status', headerName: 'Status', width: 140, renderCell: (params) => <StatusChip status={entryStatus(params.row)} /> }, { field: 'reason', headerName: 'Catatan', flex: 1, minWidth: 220, valueGetter: (value, row) => row.match_reason || row.reason || '-' }]} loading={jobsLoading} getRowId={(row) => row.bulk_upload_entry_id ?? row.id ?? row.entry_path ?? row.original_filename} pageSize={25} pageSizeOptions={[25, 50]} /><div className="mt-4"><h3 className="text-xs font-semibold text-zinc-600 mb-2">Riwayat Job</h3><CustomDataTable rows={jobs} columns={jobColumns} loading={jobsLoading} getRowId={(row) => jobId(row)} pageSize={10} pageSizeOptions={[10]} /></div></section>}
            <Dialog open={dialogOpen} onClose={() => setDialogOpen(false)} fullWidth maxWidth="lg"><DialogTitle className="!font-jakarta">{editing ? 'Edit Draft Distribusi' : 'Buat Distribusi'}</DialogTitle><DialogContent dividers className="space-y-4"><div className="grid grid-cols-1 md:grid-cols-2 gap-3"><TextField size="small" label="Judul" value={form.title} onChange={(event) => setForm((prev) => ({ ...prev, title: event.target.value }))} required /><TextField className="md:col-span-2" size="small" multiline minRows={3} label="Deskripsi" value={form.description} onChange={(event) => setForm((prev) => ({ ...prev, description: event.target.value }))} /></div><TargetPicker value={targetPayload} onChange={setTargetPayload} initialRole={targetPayload?.target_role || 'mahasiswa'} /><div className="rounded-lg border border-zinc-200 bg-zinc-50 p-3 flex items-center justify-between gap-3 flex-wrap"><div className="text-xs text-zinc-600"><strong>Preview target</strong><p>{preview ? `${preview.total_valid ?? 0} valid · ${preview.total_invalid ?? 0} invalid · ${preview.total_targets ?? 0} total` : 'Belum divalidasi.'}</p></div><Button variant="outlined" disabled={previewLoading} onClick={previewTargets} sx={{ ...buttonSx, borderColor: '#e4e4e7', color: '#3f3f46' }}>{previewLoading ? 'Memvalidasi...' : 'Preview Target'}</Button></div></DialogContent><DialogActions><Button onClick={() => setDialogOpen(false)} sx={buttonSx}>Batal</Button><Button variant="contained" disabled={saving} onClick={saveDistribution} sx={{ ...buttonSx, backgroundColor: '#2563eb' }}>Simpan Draft</Button></DialogActions></Dialog>
        </div>
    );
}
